import { readFile } from "node:fs/promises";
import test from "node:test";
import assert from "node:assert/strict";

const rootPackage = await readFile(new URL("../package.json", import.meta.url), "utf8");
const nextPackage = await readFile(new URL("../frontend-next/package.json", import.meta.url), "utf8");
const nextPackageLock = await readFile(new URL("../frontend-next/package-lock.json", import.meta.url), "utf8");
const nextConfig = await readFile(new URL("../frontend-next/next.config.mjs", import.meta.url), "utf8");
const page = await readFile(new URL("../frontend-next/app/page.tsx", import.meta.url), "utf8");
const dashboard = await readFile(new URL("../frontend-next/components/platform-dashboard.tsx", import.meta.url), "utf8");
const shell = await readFile(new URL("../frontend-next/components/app-shell.tsx", import.meta.url), "utf8");
const gallery = await readFile(new URL("../frontend-next/components/work-gallery.tsx", import.meta.url), "utf8");
const workspace = await readFile(new URL("../frontend-next/components/workspace-panel.tsx", import.meta.url), "utf8");
const accountPanel = await readFile(new URL("../frontend-next/components/account-panel.tsx", import.meta.url), "utf8");
const oauthCallbackPanel = await readFile(new URL("../frontend-next/components/oauth-callback-panel.tsx", import.meta.url), "utf8");
const createWorkbench = await readFile(new URL("../frontend-next/components/create-workbench.tsx", import.meta.url), "utf8");
const projectWorkspace = await readFile(new URL("../frontend-next/components/project-workspace.tsx", import.meta.url), "utf8");
const canvasWorkspace = await readFile(new URL("../frontend-next/components/canvas-workspace.tsx", import.meta.url), "utf8");
const adminShell = await readFile(new URL("../frontend-next/components/admin-shell.tsx", import.meta.url), "utf8");
const billingPanel = await readFile(new URL("../frontend-next/components/billing-panel.tsx", import.meta.url), "utf8");
const adminReviewPanel = await readFile(new URL("../frontend-next/components/admin-review-panel.tsx", import.meta.url), "utf8");
const templates = await readFile(new URL("../frontend-next/components/template-market.tsx", import.meta.url), "utf8");
const templateMarketplace = await readFile(new URL("../frontend-next/components/template-marketplace.tsx", import.meta.url), "utf8");
const review = await readFile(new URL("../frontend-next/components/review-status.tsx", import.meta.url), "utf8");
const workDetail = await readFile(new URL("../frontend-next/components/work-detail.tsx", import.meta.url), "utf8");
const authorProfile = await readFile(new URL("../frontend-next/components/author-profile-panel.tsx", import.meta.url), "utf8");
const createPage = await readFile(new URL("../frontend-next/app/create/page.tsx", import.meta.url), "utf8");
const workspacePage = await readFile(new URL("../frontend-next/app/workspace/[projectId]/page.tsx", import.meta.url), "utf8");
const billingPage = await readFile(new URL("../frontend-next/app/billing/page.tsx", import.meta.url), "utf8");
const templatesPage = await readFile(new URL("../frontend-next/app/templates/page.tsx", import.meta.url), "utf8");
const reviewPage = await readFile(new URL("../frontend-next/app/admin/review/page.tsx", import.meta.url), "utf8");
const workPage = await readFile(new URL("../frontend-next/app/works/[id]/page.tsx", import.meta.url), "utf8");
const userPage = await readFile(new URL("../frontend-next/app/users/[id]/page.tsx", import.meta.url), "utf8");
const layout = await readFile(new URL("../frontend-next/app/layout.tsx", import.meta.url), "utf8");
const api = await readFile(new URL("../frontend-next/lib/api.ts", import.meta.url), "utf8");
const fallbackData = await readFile(new URL("../frontend-next/lib/fallback-data.ts", import.meta.url), "utf8");
const tailwind = await readFile(new URL("../frontend-next/tailwind.config.ts", import.meta.url), "utf8");
const accountPage = await readFile(new URL("../frontend-next/app/account/page.tsx", import.meta.url), "utf8");
const oauthCallbackPage = await readFile(new URL("../frontend-next/app/account/oauth/callback/page.tsx", import.meta.url), "utf8");

test("Next 前端骨架声明 TypeScript、Tailwind 和核心依赖", () => {
  const rootManifest = JSON.parse(rootPackage);
  const manifest = JSON.parse(nextPackage);
  const lockfile = JSON.parse(nextPackageLock);
  assert.match(rootManifest.scripts["check:next"], /npm --prefix frontend-next run typecheck/);
  assert.match(rootManifest.scripts["check:next"], /npm --prefix frontend-next run build/);
  assert.match(rootManifest.scripts["check:next"], /node tests\/next_runtime_smoke\.mjs/);
  assert.equal(manifest.scripts.dev, "next dev");
  assert.equal(manifest.scripts.start, "next start");
  assert.equal(manifest.scripts.typecheck, "tsc --noEmit");
  assert.ok(manifest.dependencies.next);
  assert.match(manifest.dependencies.next, /\^16\./);
  assert.ok(manifest.dependencies.react);
  assert.ok(manifest.dependencies["lucide-react"]);
  assert.ok(manifest.dependencies["@xyflow/react"]);
  assert.match(manifest.devDependencies.postcss, /\^8\.5\./);
  assert.match(manifest.overrides.postcss, /\^8\.5\./);
  assert.ok(manifest.devDependencies.typescript);
  assert.ok(manifest.devDependencies.tailwindcss);
  assert.equal(lockfile.packages[""].dependencies.next, manifest.dependencies.next);
  assert.equal(lockfile.packages[""].dependencies["@xyflow/react"], manifest.dependencies["@xyflow/react"]);
  assert.match(nextConfig, /PLATFORM_API_BASE_URL/);
  assert.match(nextConfig, /source: "\/api\/:path\*"/);
  assert.match(nextConfig, /destination: `\$\{apiBaseUrl\}\/api\/:path\*`/);
  assert.match(nextConfig, /source: "\/storage\/:path\*"/);
});

test("Next 首页呈现用户创作入口并隐藏后台能力", () => {
  assert.match(layout, /lang="zh-CN"/);
  assert.match(layout, /漫剧工坊/);
  assert.match(page, /PlatformDashboard/);
  for (const text of ["作品广场", "开始创作", "模板市场", "脚本成片", "创建空白项目", "刷新草稿", "暂无项目草稿", "全画幅创作入口", "快速体验模板"]) {
    assert.match(`${dashboard}\n${shell}\n${gallery}\n${workspace}\n${templates}`, new RegExp(text));
  }
  assert.doesNotMatch(shell, /发布审核/);
  assert.doesNotMatch(shell, /admin\/review/);
  assert.doesNotMatch(dashboard, /ReviewStatus/);
  assert.doesNotMatch(dashboard, /apiFetch\("\/api\/health"\)/);
  assert.match(dashboard, /new URLSearchParams\(\{ sort_by: query\.sortBy \}\)/);
  assert.match(dashboard, /params\.set\("category", query\.category\)/);
  assert.match(dashboard, /params\.set\("keyword", query\.keyword\.trim\(\)\)/);
  assert.match(dashboard, /apiFetch\(`\/api\/works\?\$\{params\.toString\(\)\}`\)/);
  assert.match(dashboard, /apiFetch\("\/api\/templates"\)/);
  assert.match(workspace, /"use client"/);
  assert.match(workspace, /apiFetch\(`\/api\/projects\?owner_id=/);
  assert.match(workspace, /postJson<Project>\("\/api\/projects"/);
  assert.match(workspace, /owner_id: currentUserId\(\)/);
  assert.match(workspace, /href=\{`\/workspace\/\$\{project\.id\}`\}/);
  assert.match(gallery, /item\.cover_url/);
  assert.match(gallery, /item\.video_url/);
  assert.match(gallery, /item\.template_name/);
  assert.match(gallery, /item\.tags/);
  assert.match(gallery, /onSubmit=\{submitSearch\}/);
  assert.match(gallery, /onQueryChange/);
  assert.match(gallery, /sortOptions/);
  for (const text of ["搜索作品", "最新发布", "最多浏览", "最多点赞", "最多收藏", "成片", "模板：", "暂无匹配作品"]) {
    assert.match(gallery, new RegExp(text));
  }
  assert.doesNotMatch(`${page}\n${dashboard}`, /hero/i);
});

test("Next 前端迁移已拆分组件并提供核心路由", () => {
  assert.match(shell, /href: "\/create"/);
  assert.match(shell, /href: "\/templates"/);
  assert.match(shell, /href: "\/billing"/);
  assert.match(shell, /href: "\/account"/);
  assert.match(adminShell, /href: "\/admin\/review"/);
  assert.match(adminShell, /运营后台/);
  assert.match(workPage, /WorkDetail/);
  assert.match(userPage, /AuthorProfilePanel/);
  assert.match(workspacePage, /CanvasWorkspace/);
  assert.match(createPage, /创作流程/);
  assert.match(createPage, /CreateWorkbench/);
  assert.match(createPage, /全画幅画布/);
  assert.match(templatesPage, /TemplateMarketplace/);
  assert.match(templatesPage, /模板复刻/);
  assert.match(billingPage, /BillingPanel/);
  assert.match(billingPage, /积分充值/);
  assert.match(accountPage, /AccountPanel/);
  assert.match(accountPage, /账号令牌/);
  assert.match(`${reviewPage}\n${adminReviewPanel}`, /审核队列/);
  assert.match(reviewPage, /AdminReviewPanel/);
  assert.match(fallbackData, /短片剧集/);
  assert.match(fallbackData, /selfhost\/video_wan2\.1_fusionx/);
});

test("Next 全屏创作画布支持节点编排和平台节点运行", () => {
  assert.match(canvasWorkspace, /@xyflow\/react/);
  assert.match(canvasWorkspace, /ReactFlow/);
  assert.match(canvasWorkspace, /Background/);
  assert.match(canvasWorkspace, /Controls/);
  assert.match(canvasWorkspace, /MiniMap/);
  assert.match(canvasWorkspace, /Handle/);
  assert.match(canvasWorkspace, /Position\.Left/);
  assert.match(canvasWorkspace, /Position\.Right/);
  assert.match(canvasWorkspace, /id: "input"/);
  assert.match(canvasWorkspace, /id: "output"/);
  assert.match(canvasWorkspace, /semanticPortsForType/);
  assert.match(canvasWorkspace, /semanticPortsForNode/);
  assert.match(canvasWorkspace, /portTop/);
  assert.match(canvasWorkspace, /initialViewport/);
  assert.match(canvasWorkspace, /normalizedViewport/);
  assert.match(canvasWorkspace, /currentCanvasViewport/);
  assert.match(canvasWorkspace, /restoreCanvasViewport/);
  assert.match(canvasWorkspace, /flowInstance\.setViewport/);
  assert.match(canvasWorkspace, /flowInstance\?\.getViewport/);
  assert.match(canvasWorkspace, /CanvasViewBookmark/);
  assert.match(canvasWorkspace, /viewBookmarkStoragePrefix/);
  assert.match(canvasWorkspace, /saveCurrentViewBookmark/);
  assert.match(canvasWorkspace, /restoreViewBookmark/);
  assert.match(canvasWorkspace, /deleteViewBookmark/);
  assert.match(canvasWorkspace, /fitGraphView/);
  assert.match(canvasWorkspace, /fitSelectedNodeView/);
  assert.match(canvasWorkspace, /resetCanvasViewport/);
  assert.match(canvasWorkspace, /flowInstance\?\.fitView/);
  assert.match(canvasWorkspace, /snapToGrid/);
  assert.match(canvasWorkspace, /snapGrid=\{\[24, 24\]\}/);
  assert.match(canvasWorkspace, /toggleSnapToGrid/);
  assert.match(canvasWorkspace, /showMiniMap/);
  assert.match(canvasWorkspace, /toggleMiniMap/);
  assert.match(canvasWorkspace, /selectionOnDrag/);
  assert.match(canvasWorkspace, /toggleSelectionOnDrag/);
  assert.match(canvasWorkspace, /panOnDrag=\{!selectionOnDrag\}/);
  assert.match(canvasWorkspace, /网格吸附/);
  assert.match(canvasWorkspace, /已开启网格吸附/);
  assert.match(canvasWorkspace, /已关闭网格吸附/);
  assert.match(canvasWorkspace, /拖拽框选模式/);
  assert.match(canvasWorkspace, /空白处拖动恢复为平移画布/);
  assert.match(canvasWorkspace, /画布导航器/);
  assert.match(canvasWorkspace, /showCommandPalette/);
  assert.match(canvasWorkspace, /commandPaletteItems/);
  assert.match(canvasWorkspace, /filteredCommandPaletteItems/);
  assert.match(canvasWorkspace, /activeCommandPaletteIndex/);
  assert.match(canvasWorkspace, /activeCommandPaletteItem/);
  assert.match(canvasWorkspace, /handleCommandPaletteKeyDown/);
  assert.match(canvasWorkspace, /moveActiveCommandPaletteItem/);
  assert.match(canvasWorkspace, /runCommandPaletteItem/);
  assert.match(canvasWorkspace, /当前命令面板没有匹配命令，无法执行/);
  assert.match(canvasWorkspace, /当前命令不可执行/);
  assert.match(canvasWorkspace, /已定位命令/);
  assert.match(canvasWorkspace, /搜索命令、面板、导入导出、运行或视图操作/);
  assert.match(canvasWorkspace, /onKeyDown=\{handleCommandPaletteKeyDown\}/);
  assert.match(canvasWorkspace, /没有匹配的画布命令，请换一个关键词/);
  assert.match(canvasWorkspace, /Ctrl\/⌘ K/);
  assert.match(canvasWorkspace, /迷你地图/);
  assert.match(canvasWorkspace, /释放右下角预览空间/);
  assert.match(canvasWorkspace, /zoomCanvas/);
  assert.match(canvasWorkspace, /放大画布/);
  assert.match(canvasWorkspace, /缩小画布/);
  assert.match(canvasWorkspace, /event\.key === "\+"/);
  assert.match(canvasWorkspace, /event\.key === "-"/);
  assert.match(canvasWorkspace, /NumpadAdd/);
  assert.match(canvasWorkspace, /NumpadSubtract/);
  assert.match(canvasWorkspace, /已放大画布到/);
  assert.match(canvasWorkspace, /已缩小画布到/);
  assert.match(canvasWorkspace, /适配全部节点/);
  assert.match(canvasWorkspace, /适配选中节点/);
  assert.match(canvasWorkspace, /重置画布视口/);
  assert.match(canvasWorkspace, /copyCurrentViewLink/);
  assert.match(canvasWorkspace, /复制当前视图链接/);
  assert.match(canvasWorkspace, /viewX/);
  assert.match(canvasWorkspace, /viewY/);
  assert.match(canvasWorkspace, /viewZoom/);
  assert.match(canvasWorkspace, /已复制当前画布视图链接到系统剪贴板/);
  assert.match(canvasWorkspace, /浏览器剪贴板不可用，已把画布视图链接暂存到本地/);
  assert.match(canvasWorkspace, /已通过画布视图链接恢复缩放和位置/);
  assert.match(canvasWorkspace, /画布视图书签/);
  assert.match(canvasWorkspace, /保存当前视图/);
  assert.match(canvasWorkspace, /CanvasGraphVersion/);
  assert.match(canvasWorkspace, /graphVersionStorageKey/);
  assert.match(canvasWorkspace, /saveCurrentGraphVersion/);
  assert.match(canvasWorkspace, /restoreGraphVersion/);
  assert.match(canvasWorkspace, /deleteGraphVersion/);
  assert.match(canvasWorkspace, /exportGraphVersion/);
  assert.match(canvasWorkspace, /importGraphVersionFromClipboard/);
  assert.match(canvasWorkspace, /画布版本历史/);
  assert.match(canvasWorkspace, /保存当前版本快照/);
  assert.match(canvasWorkspace, /导出版本/);
  assert.match(canvasWorkspace, /导出最新画布版本/);
  assert.match(canvasWorkspace, /导入版本快照/);
  assert.match(canvasWorkspace, /导入画布版本快照/);
  assert.match(canvasWorkspace, /已导出并复制画布版本 ProjectGraph JSON/);
  assert.match(canvasWorkspace, /已导出画布版本 ProjectGraph JSON；浏览器剪贴板不可用，已把内容暂存到本地/);
  assert.match(canvasWorkspace, /剪贴板中没有可导入为画布版本的 ProjectGraph JSON/);
  assert.match(canvasWorkspace, /已导入画布版本快照/);
  assert.match(canvasWorkspace, /已恢复画布版本快照/);
  assert.match(canvasWorkspace, /暂无画布版本快照，可先保存当前版本/);
  assert.match(canvasWorkspace, /已保存画布视图书签/);
  assert.match(canvasWorkspace, /已恢复画布视图书签/);
  assert.match(canvasWorkspace, /已适配选区视图/);
  assert.match(canvasWorkspace, /selectAllCanvasNodes/);
  assert.match(canvasWorkspace, /invertCanvasSelection/);
  assert.match(canvasWorkspace, /clearCanvasSelection/);
  assert.match(canvasWorkspace, /全选画布节点/);
  assert.match(canvasWorkspace, /反选画布节点/);
  assert.match(canvasWorkspace, /清空当前选区/);
  assert.match(canvasWorkspace, /已全选画布节点/);
  assert.match(canvasWorkspace, /已反选画布节点/);
  assert.match(canvasWorkspace, /已清空当前节点和连线选区/);
  assert.match(canvasWorkspace, /提示词/);
  assert.match(canvasWorkspace, /首帧/);
  assert.match(canvasWorkspace, /参考图/);
  assert.match(canvasWorkspace, /成片/);
  assert.match(canvasWorkspace, /applySelectedNodePreset/);
  assert.match(canvasWorkspace, /分镜图参数预设/);
  assert.match(canvasWorkspace, /镜头视频参数预设/);
  assert.match(canvasWorkspace, /配音参数预设/);
  assert.match(canvasWorkspace, /合成参数预设/);
  assert.match(canvasWorkspace, /竖屏 9:16/);
  assert.match(canvasWorkspace, /随机 seed/);
  assert.match(canvasWorkspace, /标准 5 秒/);
  assert.match(canvasWorkspace, /女声常速/);
  assert.match(canvasWorkspace, /带字幕成片/);
  assert.match(canvasWorkspace, /id=\{port\.id\}/);
  assert.match(canvasWorkspace, /port\.side === "input"/);
  assert.match(canvasWorkspace, /edgeWithDefaultHandles/);
  assert.match(canvasWorkspace, /connectionIssueMessage/);
  assert.match(canvasWorkspace, /connectionEndpointKey/);
  assert.match(canvasWorkspace, /不能把节点连接到自身/);
  assert.match(canvasWorkspace, /请勿重复连接/);
  assert.match(canvasWorkspace, /连线规则冲突/);
  assert.match(canvasWorkspace, /sourceHandle: connection\.sourceHandle \|\| "output"/);
  assert.match(canvasWorkspace, /targetHandle: connection\.targetHandle \|\| "input"/);
  assert.match(canvasWorkspace, /insertNodeOnSelectedEdge/);
  assert.match(canvasWorkspace, /updateSelectedEdgePort/);
  assert.match(canvasWorkspace, /reverseSelectedEdge/);
  assert.match(canvasWorkspace, /端口映射/);
  assert.match(canvasWorkspace, /输出端口/);
  assert.match(canvasWorkspace, /输入端口/);
  assert.match(canvasWorkspace, /插入节点/);
  assert.match(canvasWorkspace, /插入文本节点/);
  assert.match(canvasWorkspace, /反转连线方向/);
  assert.match(canvasWorkspace, /已反转连线方向/);
  assert.match(canvasWorkspace, /反转连线失败/);
  assert.match(canvasWorkspace, /edge-insert-a/);
  assert.match(canvasWorkspace, /edge-insert-b/);
  assert.match(canvasWorkspace, /nodeTypes/);
  assert.match(canvasWorkspace, /文本节点/);
  assert.match(canvasWorkspace, /图片节点/);
  assert.match(canvasWorkspace, /视频节点/);
  assert.match(canvasWorkspace, /音频节点/);
  assert.match(canvasWorkspace, /脚本 Beta/);
  assert.match(canvasWorkspace, /分镜图生成/);
  assert.match(canvasWorkspace, /镜头视频生成/);
  assert.match(canvasWorkspace, /旁白配音/);
  assert.match(canvasWorkspace, /成片合成/);
  assert.match(canvasWorkspace, /apiFetch\(`\/api\/projects\/\$\{projectId\}\/graph\?user_id=/);
  assert.match(canvasWorkspace, /apiFetch\(`\/api\/projects\/\$\{projectId\}\/graph`/);
  assert.match(canvasWorkspace, /graph\/nodes\/\$\{selectedNode\.id\}\/run/);
  assert.match(canvasWorkspace, /window\.localStorage\.setItem\(`project_graph_/);
  assert.match(canvasWorkspace, /项目素材库/);
  assert.match(canvasWorkspace, /任务队列/);
  assert.match(canvasWorkspace, /生成过程追踪/);
  assert.match(canvasWorkspace, /素材筛选/);
  assert.match(canvasWorkspace, /没有匹配素材/);
  assert.match(canvasWorkspace, /没有匹配任务/);
  assert.match(canvasWorkspace, /全部 \$\{assets\.length\}/);
  assert.match(canvasWorkspace, /全部 \$\{tasks\.length\}/);
  assert.match(canvasWorkspace, /运行诊断/);
  assert.match(canvasWorkspace, /taskAction/);
  assert.match(canvasWorkspace, /batchFilteredTaskAction/);
  assert.match(canvasWorkspace, /focusTaskNode/);
  assert.match(canvasWorkspace, /selectFilteredTaskNodes/);
  assert.match(canvasWorkspace, /taskStatusCounts/);
  assert.match(canvasWorkspace, /assetTypeCounts/);
  assert.match(canvasWorkspace, /assetTypeFilter/);
  assert.match(canvasWorkspace, /taskStatusFilter/);
  assert.match(canvasWorkspace, /assetQuery/);
  assert.match(canvasWorkspace, /taskQuery/);
  assert.match(canvasWorkspace, /filteredAssets/);
  assert.match(canvasWorkspace, /assetNodeSpec/);
  assert.match(canvasWorkspace, /addFilteredAssetNodes/);
  assert.match(canvasWorkspace, /filteredTasks/);
  assert.match(canvasWorkspace, /搜索素材 URL、工作流、分镜/);
  assert.match(canvasWorkspace, /批量添加筛选素材到画布/);
  assert.match(canvasWorkspace, /已批量添加 .*个筛选素材到画布/);
  assert.match(canvasWorkspace, /当前筛选素材都已在画布中/);
  assert.match(canvasWorkspace, /搜索任务类型、工作流、错误/);
  assert.match(canvasWorkspace, /批量提交筛选任务/);
  assert.match(canvasWorkspace, /批量同步筛选任务/);
  assert.match(canvasWorkspace, /批量重试筛选失败任务/);
  assert.match(canvasWorkspace, /批量取消筛选任务/);
  assert.match(canvasWorkspace, /选中筛选任务关联节点/);
  assert.match(canvasWorkspace, /批量提交/);
  assert.match(canvasWorkspace, /批量同步/);
  assert.match(canvasWorkspace, /重试失败/);
  assert.match(canvasWorkspace, /取消运行/);
  assert.match(canvasWorkspace, /已批量.*任务/);
  assert.match(canvasWorkspace, /当前筛选结果没有待生成或生成中的任务可取消/);
  assert.match(canvasWorkspace, /没有匹配素材/);
  assert.match(canvasWorkspace, /没有匹配任务/);
  assert.match(canvasWorkspace, /selectedTask/);
  assert.match(canvasWorkspace, /\/api\/tasks\/\$\{taskId\}\/\$\{action\}/);
  assert.match(canvasWorkspace, /\/api\/comfy\/tasks\/\$\{taskId\}\/sync/);
  assert.match(canvasWorkspace, /ComfyUI/);
  assert.match(canvasWorkspace, /prompt_id/);
  assert.match(canvasWorkspace, /分镜列表/);
  assert.match(canvasWorkspace, /项目分镜/);
  assert.match(canvasWorkspace, /分镜生成链路/);
  assert.match(canvasWorkspace, /shotStatusCounts/);
  assert.match(canvasWorkspace, /shotStatusFilter/);
  assert.match(canvasWorkspace, /shotQuery/);
  assert.match(canvasWorkspace, /shotSort/);
  assert.match(canvasWorkspace, /shotWorkflowFilter/);
  assert.match(canvasWorkspace, /shotWorkflowShotIds/);
  assert.match(canvasWorkspace, /shotWorkflowCounts/);
  assert.match(canvasWorkspace, /selectedShotIds/);
  assert.match(canvasWorkspace, /selectedFilteredShots/);
  assert.match(canvasWorkspace, /toggleShotSelection/);
  assert.match(canvasWorkspace, /selectFilteredShots/);
  assert.match(canvasWorkspace, /selectUnlinkedFilteredShots/);
  assert.match(canvasWorkspace, /clearShotSelection/);
  assert.match(canvasWorkspace, /focusShotWorkflow/);
  assert.match(canvasWorkspace, /selectedShotBindingNodes/);
  assert.match(canvasWorkspace, /bindSelectedShotsToSelectedNodes/);
  assert.match(canvasWorkspace, /shotPatchForNode/);
  assert.match(canvasWorkspace, /filteredShots/);
  assert.match(canvasWorkspace, /搜索分镜描述、旁白、角色/);
  assert.match(canvasWorkspace, /分镜排序/);
  assert.match(canvasWorkspace, /按分镜序号升序/);
  assert.match(canvasWorkspace, /按分镜序号降序/);
  assert.match(canvasWorkspace, /按生成状态优先/);
  assert.match(canvasWorkspace, /选择当前分镜/);
  assert.match(canvasWorkspace, /选择未铺设/);
  assert.match(canvasWorkspace, /个未铺设分镜/);
  assert.match(canvasWorkspace, /清空分镜选择/);
  assert.match(canvasWorkspace, /添加选中分镜链路/);
  assert.match(canvasWorkspace, /绑定选中分镜到选区节点/);
  assert.match(canvasWorkspace, /把选中分镜绑定到选区节点/);
  assert.match(canvasWorkspace, /已把 .*个分镜绑定到选区 .*个节点/);
  assert.match(canvasWorkspace, /已清空分镜选择/);
  assert.match(canvasWorkspace, /全部链路/);
  assert.match(canvasWorkspace, /未铺设/);
  assert.match(canvasWorkspace, /已铺设/);
  assert.match(canvasWorkspace, /定位已有链路/);
  assert.match(canvasWorkspace, /暂未铺设生成链路/);
  assert.match(canvasWorkspace, /添加当前分镜链路/);
  assert.match(canvasWorkspace, /没有匹配分镜/);
  assert.match(canvasWorkspace, /当前筛选结果没有可添加的分镜/);
  assert.match(canvasWorkspace, /outlineQuery/);
  assert.match(canvasWorkspace, /outlineIssuesOnly/);
  assert.match(canvasWorkspace, /filteredGraphOutlineNodes/);
  assert.match(canvasWorkspace, /outlineIssueNodeIds/);
  assert.match(canvasWorkspace, /搜索节点标题、类型、状态/);
  assert.match(canvasWorkspace, /只看问题节点/);
  assert.match(canvasWorkspace, /selectCanvasNodesByIds/);
  assert.match(canvasWorkspace, /selectFilteredOutlineNodes/);
  assert.match(canvasWorkspace, /selectIssueOutlineNodes/);
  assert.match(canvasWorkspace, /downstreamNodeIds/);
  assert.match(canvasWorkspace, /selectSelectedUpstreamChain/);
  assert.match(canvasWorkspace, /selectSelectedDownstreamChain/);
  assert.match(canvasWorkspace, /selectSameTypeNodes/);
  assert.match(canvasWorkspace, /selectSameStatusNodes/);
  assert.match(canvasWorkspace, /selectSameColorNodes/);
  assert.match(canvasWorkspace, /selectDisabledNodes/);
  assert.match(canvasWorkspace, /selectIsolatedNodes/);
  assert.match(canvasWorkspace, /selectSourceNodes/);
  assert.match(canvasWorkspace, /selectTerminalNodes/);
  assert.match(canvasWorkspace, /selectValidationIssueNodes/);
  assert.match(canvasWorkspace, /selectTaskStatusNodes/);
  assert.match(canvasWorkspace, /selectedEdges/);
  assert.match(canvasWorkspace, /selectCanvasEdgesByIds/);
  assert.match(canvasWorkspace, /selectAllCanvasEdges/);
  assert.match(canvasWorkspace, /invertCanvasEdgeSelection/);
  assert.match(canvasWorkspace, /selectSameSourceEdges/);
  assert.match(canvasWorkspace, /selectSameTargetEdges/);
  assert.match(canvasWorkspace, /selectSameLabelEdges/);
  assert.match(canvasWorkspace, /selectSameColorEdges/);
  assert.match(canvasWorkspace, /selectSameStyleEdges/);
  assert.match(canvasWorkspace, /选中当前结果/);
  assert.match(canvasWorkspace, /选中问题节点/);
  assert.match(canvasWorkspace, /链路选择/);
  assert.match(canvasWorkspace, /选中上游链路/);
  assert.match(canvasWorkspace, /选中下游链路/);
  assert.match(canvasWorkspace, /选中同类型节点/);
  assert.match(canvasWorkspace, /选中同状态节点/);
  assert.match(canvasWorkspace, /选中同标记节点/);
  assert.match(canvasWorkspace, /选中禁用节点/);
  assert.match(canvasWorkspace, /选中孤立节点/);
  assert.match(canvasWorkspace, /选中起点节点/);
  assert.match(canvasWorkspace, /选中终点节点/);
  assert.match(canvasWorkspace, /选中错误节点/);
  assert.match(canvasWorkspace, /选中提醒节点/);
  assert.match(canvasWorkspace, /选中运行中任务节点/);
  assert.match(canvasWorkspace, /选中失败任务节点/);
  assert.match(canvasWorkspace, /连线选择/);
  assert.match(canvasWorkspace, /全选画布连线/);
  assert.match(canvasWorkspace, /反选画布连线/);
  assert.match(canvasWorkspace, /画布暂无连线，无法全选/);
  assert.match(canvasWorkspace, /画布暂无连线，无法反选/);
  assert.match(canvasWorkspace, /已全选画布连线/);
  assert.match(canvasWorkspace, /已反选画布连线/);
  assert.match(canvasWorkspace, /全部连线/);
  assert.match(canvasWorkspace, /反选连线/);
  assert.match(canvasWorkspace, /选中同起点连线/);
  assert.match(canvasWorkspace, /选中同终点连线/);
  assert.match(canvasWorkspace, /选中同标签连线/);
  assert.match(canvasWorkspace, /选中同颜色连线/);
  assert.match(canvasWorkspace, /选中同样式连线/);
  assert.match(canvasWorkspace, /当前连线没有标签/);
  assert.match(canvasWorkspace, /可继续禁用、标记、改样式或删除/);
  assert.match(canvasWorkspace, /已选中\$\{label\}/);
  assert.match(canvasWorkspace, /同类型/);
  assert.match(canvasWorkspace, /同状态/);
  assert.match(canvasWorkspace, /同标记/);
  assert.match(canvasWorkspace, /画布暂无禁用节点/);
  assert.match(canvasWorkspace, /画布暂无孤立节点/);
  assert.match(canvasWorkspace, /画布暂无可选起点节点/);
  assert.match(canvasWorkspace, /画布暂无可选终点节点/);
  assert.match(canvasWorkspace, /画布暂无错误节点/);
  assert.match(canvasWorkspace, /画布暂无提醒节点/);
  assert.match(canvasWorkspace, /画布暂无运行中任务节点/);
  assert.match(canvasWorkspace, /画布暂无失败任务节点/);
  assert.match(canvasWorkspace, /当前下游链路/);
  assert.match(canvasWorkspace, /可继续整理、打组、复制或运行链路/);
  assert.match(canvasWorkspace, /没有匹配的大纲节点/);
  assert.match(canvasWorkspace, /添加分镜链路/);
  assert.match(canvasWorkspace, /添加当前分镜链路/);
  assert.match(canvasWorkspace, /addShotWorkflow/);
  assert.match(canvasWorkspace, /addAllShotWorkflows/);
  assert.match(canvasWorkspace, /buildShotWorkflow/);
  assert.match(canvasWorkspace, /paletteNodeDragType/);
  assert.match(canvasWorkspace, /handlePaletteNodeDragStart/);
  assert.match(canvasWorkspace, /recentNodeStorageKey/);
  assert.match(canvasWorkspace, /recentNodeTypes/);
  assert.match(canvasWorkspace, /recentAddableNodes/);
  assert.match(canvasWorkspace, /rememberRecentNodeType/);
  assert.match(canvasWorkspace, /最近使用节点/);
  assert.match(canvasWorkspace, /application\/x-video-gen-node-type/);
  assert.match(canvasWorkspace, /draggable/);
  assert.match(canvasWorkspace, /已在落点添加/);
  assert.match(canvasWorkspace, /addConnectedNodeFromSelected/);
  assert.match(canvasWorkspace, /快速添加下游/);
  assert.match(canvasWorkspace, /添加下游分镜图/);
  assert.match(canvasWorkspace, /已从当前节点添加并连接/);
  assert.match(canvasWorkspace, /addUpstreamNodeForSelected/);
  assert.match(canvasWorkspace, /快速添加上游/);
  assert.match(canvasWorkspace, /添加上游文本/);
  assert.match(canvasWorkspace, /已为当前节点添加并连接/);
  assert.match(canvasWorkspace, /保存画布/);
  assert.match(canvasWorkspace, /画布自检/);
  assert.match(canvasWorkspace, /运行前检查/);
  assert.match(canvasWorkspace, /运行前缺口/);
  assert.match(canvasWorkspace, /当前节点暂不能直接运行/);
  assert.match(canvasWorkspace, /validateCanvasGraph/);
  assert.match(canvasWorkspace, /GraphValidationIssue/);
  assert.match(canvasWorkspace, /blockingValidationIssues/);
  assert.match(canvasWorkspace, /showRunBlockingIssue/);
  assert.match(canvasWorkspace, /selectedRunBlockingIssues/);
  assert.match(canvasWorkspace, /incomingNodeData/);
  assert.match(canvasWorkspace, /firstNonEmpty/);
  assert.match(canvasWorkspace, /focusCanvasNode/);
  assert.match(canvasWorkspace, /自检通过/);
  assert.match(canvasWorkspace, /导出工作流/);
  assert.match(canvasWorkspace, /导入工作流/);
  assert.match(canvasWorkspace, /导入工作流 JSON/);
  assert.match(canvasWorkspace, /MediaPreview/);
  assert.match(canvasWorkspace, /mediaUrlFromData/);
  assert.match(canvasWorkspace, /mediaKindFromData/);
  assert.match(canvasWorkspace, /素材预览/);
  assert.match(canvasWorkspace, /上游输入/);
  assert.match(canvasWorkspace, /填充参数/);
  assert.match(canvasWorkspace, /upstreamInputEntries/);
  assert.match(canvasWorkspace, /fillSelectedFromUpstream/);
  assert.match(canvasWorkspace, /节点快捷菜单/);
  assert.match(canvasWorkspace, /openNodeContextMenu/);
  assert.match(canvasWorkspace, /onNodeContextMenu/);
  assert.match(canvasWorkspace, /复制上游链路/);
  assert.match(canvasWorkspace, /撤销/);
  assert.match(canvasWorkspace, /重做/);
  assert.match(canvasWorkspace, /groupSelectedNodes/);
  assert.match(canvasWorkspace, /ungroupSelectedNodes/);
  assert.match(canvasWorkspace, /group_id/);
  assert.match(canvasWorkspace, /group_title/);
  assert.match(canvasWorkspace, /打组选区/);
  assert.match(canvasWorkspace, /取消分组/);
  assert.match(canvasWorkspace, /selectedGroupIds/);
  assert.match(canvasWorkspace, /selectedGroupTitleValue/);
  assert.match(canvasWorkspace, /updateSelectedGroupTitle/);
  assert.match(canvasWorkspace, /selectSelectedGroups/);
  assert.match(canvasWorkspace, /分组名称/);
  assert.match(canvasWorkspace, /多个分组，将统一改名/);
  assert.match(canvasWorkspace, /选中同组节点/);
  assert.match(canvasWorkspace, /选中同组/);
  assert.match(canvasWorkspace, /当前分组/);
  assert.match(canvasWorkspace, /当前多个分组/);
  assert.match(canvasWorkspace, /已更新分组名称/);
  assert.match(canvasWorkspace, /payload\.note/);
  assert.match(canvasWorkspace, /data\.note/);
  assert.match(canvasWorkspace, /节点备注/);
  assert.match(canvasWorkspace, /记录节点用途、模型选择或后续修改点/);
  assert.match(canvasWorkspace, /备注：/);
  assert.match(canvasWorkspace, /nodeMarkerColors/);
  assert.match(canvasWorkspace, /nodeMarkerColorByValue/);
  assert.match(canvasWorkspace, /setSelectedNodesColor/);
  assert.match(canvasWorkspace, /节点颜色标记/);
  assert.match(canvasWorkspace, /选区颜色标记/);
  assert.match(canvasWorkspace, /标记：/);
  assert.match(canvasWorkspace, /已设置选区颜色标记/);
  assert.match(canvasWorkspace, /selectedRenamePrefix/);
  assert.match(canvasWorkspace, /renameSelectedNodesWithPrefix/);
  assert.match(canvasWorkspace, /选区批量命名/);
  assert.match(canvasWorkspace, /请输入选区批量命名前缀/);
  assert.match(canvasWorkspace, /已按前缀/);
  assert.match(canvasWorkspace, /setSelectedSelectionEdgesDisabled/);
  assert.match(canvasWorkspace, /deleteSelectedSelectionEdges/);
  assert.match(canvasWorkspace, /setSelectedSelectionEdgesColor/);
  assert.match(canvasWorkspace, /setSelectedSelectionEdgesStyle/);
  assert.match(canvasWorkspace, /disconnectSelectedNodes/);
  assert.match(canvasWorkspace, /选区内部连线/);
  assert.match(canvasWorkspace, /禁用内部连线/);
  assert.match(canvasWorkspace, /启用内部连线/);
  assert.match(canvasWorkspace, /断开选区连线/);
  assert.match(canvasWorkspace, /断开节点连线/);
  assert.match(canvasWorkspace, /已断开选区相关连线/);
  assert.match(canvasWorkspace, /已断开当前节点相关连线/);
  assert.match(canvasWorkspace, /当前节点没有可断开的连线/);
  assert.match(canvasWorkspace, /删除内部连线/);
  assert.match(canvasWorkspace, /已删除选区内部连线/);
  assert.match(canvasWorkspace, /已设置选区内部连线颜色/);
  assert.match(canvasWorkspace, /已设置选区内部连线样式/);
  assert.match(canvasWorkspace, /当前选区没有内部连线/);
  assert.match(canvasWorkspace, /toggleSelectedNodeCollapsed/);
  assert.match(canvasWorkspace, /setSelectedNodesCollapsed/);
  assert.match(canvasWorkspace, /折叠节点内容/);
  assert.match(canvasWorkspace, /折叠节点/);
  assert.match(canvasWorkspace, /展开节点/);
  assert.match(canvasWorkspace, /折叠选区/);
  assert.match(canvasWorkspace, /展开选区/);
  assert.match(canvasWorkspace, /已折叠/);
  assert.match(canvasWorkspace, /节点已折叠/);
  assert.match(canvasWorkspace, /节点已展开/);
  assert.match(canvasWorkspace, /alignSelectedNodes/);
  assert.match(canvasWorkspace, /nudgeSelectedNodes/);
  assert.match(canvasWorkspace, /ArrowLeft/);
  assert.match(canvasWorkspace, /ArrowRight/);
  assert.match(canvasWorkspace, /ArrowUp/);
  assert.match(canvasWorkspace, /ArrowDown/);
  assert.match(canvasWorkspace, /请先选择节点，再用方向键微调位置/);
  assert.match(canvasWorkspace, /选区节点均已锁定，请先解锁再移动/);
  assert.match(canvasWorkspace, /已向\$\{direction\}微调选区/);
  assert.match(canvasWorkspace, /setSelectedNodesLayer/);
  assert.match(canvasWorkspace, /nodeLayerValue/);
  assert.match(canvasWorkspace, /layer_z/);
  assert.match(canvasWorkspace, /zIndex/);
  assert.match(canvasWorkspace, /BringToFront/);
  assert.match(canvasWorkspace, /SendToBack/);
  assert.match(canvasWorkspace, /请先选择节点，再调整层级/);
  assert.match(canvasWorkspace, /已\$\{mode === "front" \? "置顶" : "置底"\}选区/);
  assert.match(canvasWorkspace, /对齐与分布/);
  assert.match(canvasWorkspace, /左对齐选区/);
  assert.match(canvasWorkspace, /水平居中对齐选区/);
  assert.match(canvasWorkspace, /右对齐选区/);
  assert.match(canvasWorkspace, /顶部对齐选区/);
  assert.match(canvasWorkspace, /垂直居中对齐选区/);
  assert.match(canvasWorkspace, /底部对齐选区/);
  assert.match(canvasWorkspace, /水平等距分布选区/);
  assert.match(canvasWorkspace, /垂直等距分布选区/);
  assert.match(canvasWorkspace, /"水平居中对齐"/);
  assert.match(canvasWorkspace, /"垂直居中对齐"/);
  assert.match(canvasWorkspace, /"右对齐"/);
  assert.match(canvasWorkspace, /"底部对齐"/);
  assert.match(canvasWorkspace, /\$\{label\}选区/);
  assert.match(canvasWorkspace, /\$\{selectedNodes\.length\} 个节点/);
  assert.match(canvasWorkspace, /工作流组/);
  assert.match(canvasWorkspace, /GraphHistorySnapshot/);
  assert.match(canvasWorkspace, /rememberGraphHistory/);
  assert.match(canvasWorkspace, /rememberSelectedNodeEdit/);
  assert.match(canvasWorkspace, /onFocus=\{rememberSelectedNodeEdit\}/);
  assert.match(canvasWorkspace, /function applySelectedNodePreset[\s\S]*rememberGraphHistory/);
  assert.match(canvasWorkspace, /undoGraphChange/);
  assert.match(canvasWorkspace, /redoGraphChange/);
  assert.match(canvasWorkspace, /节点大纲/);
  assert.match(canvasWorkspace, /流程导航/);
  assert.match(canvasWorkspace, /graphOutlineNodes/);
  assert.match(canvasWorkspace, /terminalNodeIdSet/);
  assert.match(canvasWorkspace, /runNodeChain/);
  assert.match(canvasWorkspace, /exportWorkflowJson/);
  assert.match(canvasWorkspace, /exportSelectedWorkflowJson/);
  assert.match(canvasWorkspace, /importWorkflowJson/);
  assert.match(canvasWorkspace, /importWorkflowJson\("replace"\)/);
  assert.match(canvasWorkspace, /importWorkflowJson\("append"\)/);
  assert.match(canvasWorkspace, /loadImportJsonFile/);
  assert.match(canvasWorkspace, /loadImportJsonFromClipboard/);
  assert.match(canvasWorkspace, /fallbackText/);
  assert.match(canvasWorkspace, /ProjectGraph JSON/);
  assert.match(canvasWorkspace, /选择 JSON 文件导入/);
  assert.match(canvasWorkspace, /从剪贴板读取 ProjectGraph JSON/);
  assert.match(canvasWorkspace, /替换当前画布/);
  assert.match(canvasWorkspace, /追加导入/);
  assert.match(canvasWorkspace, /已替换当前画布工作流/);
  assert.match(canvasWorkspace, /已追加导入工作流/);
  assert.match(canvasWorkspace, /替换当前画布前会写入撤销历史/);
  assert.match(canvasWorkspace, /已下载并复制工作流 ProjectGraph JSON/);
  assert.match(canvasWorkspace, /已下载工作流 ProjectGraph JSON；浏览器剪贴板不可用，已把内容暂存到本地/);
  assert.match(canvasWorkspace, /剪贴板中没有可导入的 ProjectGraph JSON/);
  assert.match(canvasWorkspace, /已从剪贴板读取 ProjectGraph JSON/);
  assert.match(canvasWorkspace, /已读取导入文件/);
  assert.match(canvasWorkspace, /请选择从画布导出的 JSON 文件/);
  assert.match(canvasWorkspace, /导入文件为空，请选择有效的 ProjectGraph JSON 文件/);
  assert.match(canvasWorkspace, /运行节点/);
  assert.match(canvasWorkspace, /运行链路/);
  assert.match(canvasWorkspace, /复制节点/);
  assert.match(canvasWorkspace, /剪切节点/);
  assert.match(canvasWorkspace, /copySelectedNodeId/);
  assert.match(canvasWorkspace, /copySelectedNodeParams/);
  assert.match(canvasWorkspace, /copySelectedNodeLink/);
  assert.match(canvasWorkspace, /new URLSearchParams\(window\.location\.search\)/);
  assert.match(canvasWorkspace, /url\.searchParams\.set\("node", selectedNode\.id\)/);
  assert.match(canvasWorkspace, /已通过节点链接定位到画布节点/);
  assert.match(canvasWorkspace, /节点链接已打开，但当前画布没有找到对应节点/);
  assert.match(canvasWorkspace, /复制节点 ID/);
  assert.match(canvasWorkspace, /复制节点参数 JSON/);
  assert.match(canvasWorkspace, /复制节点定位链接/);
  assert.match(canvasWorkspace, /复制链接/);
  assert.match(canvasWorkspace, /已复制节点 ID 到系统剪贴板/);
  assert.match(canvasWorkspace, /已复制节点参数 JSON 到系统剪贴板/);
  assert.match(canvasWorkspace, /已复制节点定位链接到系统剪贴板/);
  assert.match(canvasWorkspace, /浏览器剪贴板不可用，已把节点定位链接暂存到本地/);
  assert.match(canvasWorkspace, /浏览器剪贴板不可用，已把节点参数 JSON 暂存到本地/);
  assert.match(canvasWorkspace, /置顶节点/);
  assert.match(canvasWorkspace, /置底节点/);
  assert.match(canvasWorkspace, /复制链路/);
  assert.match(canvasWorkspace, /粘贴链路/);
  assert.match(canvasWorkspace, /选区操作/);
  assert.match(canvasWorkspace, /复制选区/);
  assert.match(canvasWorkspace, /剪切选区/);
  assert.match(canvasWorkspace, /导出选区 JSON/);
  assert.match(canvasWorkspace, /downloadJsonFile/);
  assert.match(canvasWorkspace, /已下载并复制选区 ProjectGraph JSON/);
  assert.match(canvasWorkspace, /已下载选区 ProjectGraph JSON；浏览器剪贴板不可用，已把内容暂存到本地/);
  assert.match(canvasWorkspace, /置顶选区/);
  assert.match(canvasWorkspace, /置底选区/);
  assert.match(canvasWorkspace, /整理选区/);
  assert.match(canvasWorkspace, /connectSelectedNodesInOrder/);
  assert.match(canvasWorkspace, /串联选区/);
  assert.match(canvasWorkspace, /已按从左到右顺序串联选区/);
  assert.match(canvasWorkspace, /禁用选区/);
  assert.match(canvasWorkspace, /锁定选区/);
  assert.match(canvasWorkspace, /锁定节点/);
  assert.match(canvasWorkspace, /解锁节点/);
  assert.match(canvasWorkspace, /锁定节点位置/);
  assert.match(canvasWorkspace, /toggleSelectedNodeLock/);
  assert.match(canvasWorkspace, /draggable: item\.data\?\.locked !== true/);
  assert.match(canvasWorkspace, /节点已锁定，请先解锁再删除/);
  assert.match(canvasWorkspace, /禁用节点/);
  assert.match(canvasWorkspace, /启用节点/);
  assert.match(canvasWorkspace, /禁用节点运行/);
  assert.match(canvasWorkspace, /toggleSelectedNodeDisabled/);
  assert.match(canvasWorkspace, /isNodeDisabled/);
  assert.match(canvasWorkspace, /跳过 .*禁用节点/);
  assert.match(canvasWorkspace, /节点类型/);
  assert.match(canvasWorkspace, /updateSelectedNodeType/);
  assert.match(canvasWorkspace, /节点类型已切换为/);
  assert.match(canvasWorkspace, /删除节点/);
  assert.match(canvasWorkspace, /upstreamNodeIds/);
  assert.match(canvasWorkspace, /orderedChainNodes/);
  assert.match(canvasWorkspace, /selectedEdge/);
  assert.match(canvasWorkspace, /onEdgeClick/);
  assert.match(canvasWorkspace, /onEdgeContextMenu/);
  assert.match(canvasWorkspace, /连线编辑/);
  assert.match(canvasWorkspace, /连线标签/);
  assert.match(canvasWorkspace, /copySelectedEdgeId/);
  assert.match(canvasWorkspace, /copySelectedEdgeParams/);
  assert.match(canvasWorkspace, /copySelectedEdgeLink/);
  assert.match(canvasWorkspace, /url\.searchParams\.set\("edge", selectedEdge\.id\)/);
  assert.match(canvasWorkspace, /已通过连线链接定位到画布连线/);
  assert.match(canvasWorkspace, /连线链接已打开，但当前画布没有找到对应连线/);
  assert.match(canvasWorkspace, /复制连线 ID/);
  assert.match(canvasWorkspace, /复制连线参数 JSON/);
  assert.match(canvasWorkspace, /复制连线定位链接/);
  assert.match(canvasWorkspace, /已复制连线 ID 到系统剪贴板/);
  assert.match(canvasWorkspace, /已复制连线参数 JSON 到系统剪贴板/);
  assert.match(canvasWorkspace, /已复制连线定位链接到系统剪贴板/);
  assert.match(canvasWorkspace, /浏览器剪贴板不可用，已把连线定位链接暂存到本地/);
  assert.match(canvasWorkspace, /edgeMarkerColors/);
  assert.match(canvasWorkspace, /edgeMarkerColorByValue/);
  assert.match(canvasWorkspace, /edge_color/);
  assert.match(canvasWorkspace, /updateSelectedEdgeColor/);
  assert.match(canvasWorkspace, /连线颜色标记/);
  assert.match(canvasWorkspace, /已将 \$\{selectedEdgeIds\.size\} 条连线颜色标记设置为/);
  assert.match(canvasWorkspace, /edgeLineStyles/);
  assert.match(canvasWorkspace, /edgeLineStyleByValue/);
  assert.match(canvasWorkspace, /edge_style/);
  assert.match(canvasWorkspace, /updateSelectedEdgeStyle/);
  assert.match(canvasWorkspace, /连线样式/);
  assert.match(canvasWorkspace, /虚线参考/);
  assert.match(canvasWorkspace, /重点主链路/);
  assert.match(canvasWorkspace, /已将 \$\{selectedEdgeIds\.size\} 条连线样式设置为/);
  assert.match(canvasWorkspace, /禁用这条连线/);
  assert.match(canvasWorkspace, /禁用连线/);
  assert.match(canvasWorkspace, /启用连线/);
  assert.match(canvasWorkspace, /删除连线/);
  assert.match(canvasWorkspace, /updateSelectedEdgeLabel/);
  assert.match(canvasWorkspace, /toggleSelectedEdgeDisabled/);
  assert.match(canvasWorkspace, /isEdgeDisabled/);
  assert.match(canvasWorkspace, /activeGraphEdges/);
  assert.match(canvasWorkspace, /deleteSelectedEdge/);
  assert.match(canvasWorkspace, /runSelectedChain/);
  assert.match(canvasWorkspace, /runSelectedNodes/);
  assert.match(canvasWorkspace, /运行全图/);
  assert.match(canvasWorkspace, /运行选区/);
  assert.match(canvasWorkspace, /正在运行选区/);
  assert.match(canvasWorkspace, /选区运行完成/);
  assert.match(canvasWorkspace, /整理画布/);
  assert.match(canvasWorkspace, /terminalNodeIds/);
  assert.match(canvasWorkspace, /orderedGraphNodes/);
  assert.match(canvasWorkspace, /layoutGraphNodes/);
  assert.match(canvasWorkspace, /runCanvasGraph/);
  assert.match(canvasWorkspace, /autoLayoutGraph/);
  assert.match(canvasWorkspace, /duplicateSelectedNode/);
  assert.match(canvasWorkspace, /duplicateSelectedNodes/);
  assert.match(canvasWorkspace, /copySelectedNodes/);
  assert.match(canvasWorkspace, /copyGraphSnapshotToClipboard/);
  assert.match(canvasWorkspace, /parseClipboardGraphSnapshot/);
  assert.match(canvasWorkspace, /cutSelectedNodes/);
  assert.match(canvasWorkspace, /event\.key\.toLowerCase\(\) === "x"/);
  assert.match(canvasWorkspace, /已剪切选区到系统剪贴板/);
  assert.match(canvasWorkspace, /已剪切选区到本地画布剪贴板/);
  assert.match(canvasWorkspace, /请先框选或点选节点，再剪切选区/);
  assert.match(canvasWorkspace, /选区节点均已锁定，请先解锁再剪切/);
  assert.match(canvasWorkspace, /deleteSelectedNodes/);
  assert.match(canvasWorkspace, /autoLayoutSelectedNodes/);
  assert.match(canvasWorkspace, /setSelectedNodesDisabled/);
  assert.match(canvasWorkspace, /copySelectedChain/);
  assert.match(canvasWorkspace, /expandSelectedNodesToVideoGeneration/);
  assert.match(canvasWorkspace, /选区生成视频链/);
  assert.match(canvasWorkspace, /生成视频链/);
  assert.match(canvasWorkspace, /已为选区末端创建/);
  assert.match(canvasWorkspace, /expandSelectedNodesToTtsGeneration/);
  assert.match(canvasWorkspace, /选区生成配音链/);
  assert.match(canvasWorkspace, /生成配音链/);
  assert.match(canvasWorkspace, /旁白配音节点/);
  assert.match(canvasWorkspace, /collectSelectedNodesToCompose/);
  assert.match(canvasWorkspace, /选区汇聚到合成节点/);
  assert.match(canvasWorkspace, /汇聚到合成节点/);
  assert.match(canvasWorkspace, /composeTargetHandleForNode/);
  assert.match(canvasWorkspace, /视频合成输入/);
  assert.match(canvasWorkspace, /配音合成输入/);
  assert.match(canvasWorkspace, /字幕合成输入/);
  assert.match(canvasWorkspace, /connectSelectedNodesToExistingCompose/);
  assert.match(canvasWorkspace, /选区接入已有合成节点/);
  assert.match(canvasWorkspace, /接入已有合成/);
  assert.match(canvasWorkspace, /已将选区末端 .*接入已有合成节点/);
  assert.match(canvasWorkspace, /nodeParameterPresets/);
  assert.match(canvasWorkspace, /applySelectedNodesParameterPreset/);
  assert.match(canvasWorkspace, /选区批量参数预设/);
  assert.match(canvasWorkspace, /已为选区 .*个节点应用参数预设/);
  assert.match(canvasWorkspace, /已将选区末端/);
  assert.match(canvasWorkspace, /pasteCopiedSelection/);
  assert.match(canvasWorkspace, /pasteCopiedSelectionFromCanvasContext/);
  assert.match(canvasWorkspace, /currentViewportCenter/);
  assert.match(canvasWorkspace, /offsetX/);
  assert.match(canvasWorkspace, /已复制选区到系统剪贴板/);
  assert.match(canvasWorkspace, /已复制选区到本地画布剪贴板/);
  assert.match(canvasWorkspace, /已复制链路到系统剪贴板/);
  assert.match(canvasWorkspace, /已粘贴链路到当前视图中心/);
  assert.match(canvasWorkspace, /已粘贴链路到画布右键位置/);
  assert.match(canvasWorkspace, /CanvasEventLogEntry/);
  assert.match(canvasWorkspace, /eventLogStoragePrefix/);
  assert.match(canvasWorkspace, /canvasEventLog/);
  assert.match(canvasWorkspace, /filteredCanvasEventLog/);
  assert.match(canvasWorkspace, /exportCanvasEventLog/);
  assert.match(canvasWorkspace, /project_graph_event_log_export_/);
  assert.match(canvasWorkspace, /画布事件日志/);
  assert.match(canvasWorkspace, /追踪保存、运行、导入导出、复制粘贴和失败提示/);
  assert.match(canvasWorkspace, /搜索事件内容或时间/);
  assert.match(canvasWorkspace, /已导出并复制画布事件日志/);
  assert.match(canvasWorkspace, /已导出画布事件日志；浏览器剪贴板不可用，已把内容暂存到本地/);
  assert.match(canvasWorkspace, /暂无画布事件，保存、运行、导入导出或复制粘贴后会自动记录/);
  assert.match(canvasWorkspace, /没有匹配事件，请调整关键词/);
  assert.match(canvasWorkspace, /StickyNote/);
  assert.match(canvasWorkspace, /comment: "画布批注"/);
  assert.match(canvasWorkspace, /记录制作意图、审核意见和修改点/);
  assert.match(canvasWorkspace, /批注内容/);
  assert.match(canvasWorkspace, /addNodeAtPosition\("comment"/);
  assert.match(canvasWorkspace, /isCommentNode/);
  assert.match(canvasWorkspace, /isRunnableNode/);
  assert.match(canvasWorkspace, /画布批注仅用于说明和协作，不会提交生成任务/);
  assert.match(canvasWorkspace, /type === "comment"\) continue/);
  assert.match(canvasWorkspace, /禁用节点或批注节点/);
  assert.match(canvasWorkspace, /批注节点不会自动连线/);
  assert.match(canvasWorkspace, /handleCanvasDoubleClick/);
  assert.match(canvasWorkspace, /canvasContextMenu/);
  assert.match(canvasWorkspace, /openCanvasContextMenu/);
  assert.match(canvasWorkspace, /addNodeFromCanvasContext/);
  assert.match(canvasWorkspace, /addWorkflowPresetFromCanvasContext/);
  assert.match(canvasWorkspace, /addCustomWorkflowPresetFromCanvasContext/);
  assert.match(canvasWorkspace, /已在画布当前位置添加工作流预设/);
  assert.match(canvasWorkspace, /已在画布当前位置添加自定义预设/);
  assert.match(canvasWorkspace, /onPaneContextMenu=\{openCanvasContextMenu\}/);
  assert.match(canvasWorkspace, /画布快捷菜单/);
  assert.match(canvasWorkspace, /在此处添加节点或工作流/);
  assert.match(canvasWorkspace, /粘贴到此处/);
  assert.match(canvasWorkspace, /已通过画布右键菜单添加/);
  assert.match(canvasWorkspace, /handleCanvasDrop/);
  assert.match(canvasWorkspace, /handleCanvasKeyDown/);
  assert.match(canvasWorkspace, /project_graph_clipboard_/);
  assert.match(canvasWorkspace, /添加节点/);
  assert.match(canvasWorkspace, /搜索图片、视频、配音、合成/);
  assert.match(canvasWorkspace, /handlePaletteSearchKeyDown/);
  assert.match(canvasWorkspace, /addFirstFilteredPaletteNode/);
  assert.match(canvasWorkspace, /activePaletteNodeIndex/);
  assert.match(canvasWorkspace, /activePaletteNode/);
  assert.match(canvasWorkspace, /moveActivePaletteNode/);
  assert.match(canvasWorkspace, /ArrowDown/);
  assert.match(canvasWorkspace, /ArrowUp/);
  assert.match(canvasWorkspace, /当前节点面板没有匹配节点，无法切换/);
  assert.match(canvasWorkspace, /已定位节点面板项/);
  assert.match(canvasWorkspace, /当前节点面板没有匹配节点，无法快速添加/);
  assert.match(canvasWorkspace, /已关闭节点面板/);
  assert.match(canvasWorkspace, /onKeyDown=\{handlePaletteSearchKeyDown\}/);
  assert.match(canvasWorkspace, /paletteCategoryFilter/);
  assert.match(canvasWorkspace, /节点分类筛选/);
  assert.match(canvasWorkspace, /没有匹配节点，请切换分类或调整关键词/);
  assert.match(canvasWorkspace, /favoriteNodeStorageKey/);
  assert.match(canvasWorkspace, /favoriteNodeTypes/);
  assert.match(canvasWorkspace, /收藏节点/);
  assert.match(canvasWorkspace, /已收藏\$\{nodeLabels\[type\]\}，会显示在收藏节点区/);
  assert.match(canvasWorkspace, /已取消收藏\$\{nodeLabels\[type\]\}/);
  assert.match(canvasWorkspace, /工作流预设/);
  assert.match(canvasWorkspace, /我的工作流预设/);
  assert.match(canvasWorkspace, /保存当前画布为预设/);
  assert.match(canvasWorkspace, /CustomWorkflowPreset/);
  assert.match(canvasWorkspace, /customPresetStorageKey/);
  assert.match(canvasWorkspace, /customWorkflowPresets/);
  assert.match(canvasWorkspace, /saveCurrentWorkflowAsPreset/);
  assert.match(canvasWorkspace, /saveSelectedWorkflowAsPreset/);
  assert.match(canvasWorkspace, /addCustomWorkflowPreset/);
  assert.match(canvasWorkspace, /exportCustomWorkflowPreset/);
  assert.match(canvasWorkspace, /importCustomWorkflowPresetFromClipboard/);
  assert.match(canvasWorkspace, /导出预设/);
  assert.match(canvasWorkspace, /从剪贴板导入预设/);
  assert.match(canvasWorkspace, /已导出并复制预设 ProjectGraph JSON/);
  assert.match(canvasWorkspace, /已导出预设 ProjectGraph JSON；浏览器剪贴板不可用，已把内容暂存到本地/);
  assert.match(canvasWorkspace, /剪贴板中没有可导入为预设的 ProjectGraph JSON/);
  assert.match(canvasWorkspace, /已导入预设到我的工作流/);
  assert.match(canvasWorkspace, /deleteCustomWorkflowPreset/);
  assert.match(canvasWorkspace, /保存选区为预设/);
  assert.match(canvasWorkspace, /已保存选区为预设/);
  assert.match(canvasWorkspace, /选区片段/);
  assert.match(canvasWorkspace, /脚本拆解分镜/);
  assert.match(canvasWorkspace, /首帧图生视频/);
  assert.match(canvasWorkspace, /旁白字幕合成/);
  assert.match(canvasWorkspace, /addWorkflowPreset/);
  assert.match(canvasWorkspace, /平台生成/);
  assert.match(canvasWorkspace, /素材节点/);
  assert.match(canvasWorkspace, /绑定分镜/);
  assert.match(canvasWorkspace, /从连线或运行时补全/);
  assert.match(canvasWorkspace, /首帧图片 URL/);
  assert.match(canvasWorkspace, /zh-CN-XiaoxiaoNeural/);
  assert.match(canvasWorkspace, /合成字幕/);
  assert.match(api, /export type ProjectGraph/);
  assert.match(api, /export type ProjectGraphNode/);
  assert.match(api, /export type ProjectGraphEdge/);
});

test("Next 账号页支持注册登录和本地令牌管理", () => {
  assert.match(accountPanel, /"use client"/);
  assert.match(accountPanel, /postJson<AuthResponse>\("\/api\/auth\/register"/);
  assert.match(accountPanel, /postJson<AuthResponse>\("\/api\/auth\/login"/);
  assert.match(accountPanel, /postJson<AuthResponse>\("\/api\/auth\/session\/refresh"/);
  assert.match(accountPanel, /apiFetch\("\/api\/auth\/session\/me"\)/);
  assert.match(accountPanel, /apiFetch\(`\/api\/auth\/oauth\/\$\{encodeURIComponent\(provider\)\}\/start\?next_url=/);
  assert.match(accountPanel, /encodeURIComponent\("\/account\/oauth\/callback"\)/);
  assert.match(accountPanel, /window\.location\.href = authorizationUrl/);
  assert.match(oauthCallbackPanel, /"use client"/);
  assert.match(oauthCallbackPanel, /window\.location\.hash/);
  assert.match(oauthCallbackPanel, /saveUserSessionToken\(token\)/);
  assert.match(oauthCallbackPanel, /saveCurrentUser\(callbackUser\)/);
  assert.match(oauthCallbackPanel, /window\.history\.replaceState/);
  assert.match(oauthCallbackPage, /OAuthCallbackPanel/);
  assert.match(accountPanel, /savePlatformApiToken\(platformToken\)/);
  assert.match(accountPanel, /saveUserSessionToken\(response\.token\)/);
  assert.match(accountPanel, /saveCurrentUser\(response\.user\)/);
  for (const text of ["平台 API Token", "保存平台访问令牌", "注册账号", "刷新会话", "校验当前会话", "第三方登录渠道", "发起第三方登录", "第三方登录回调", "返回账号页"]) {
    assert.match(`${accountPanel}\n${accountPage}\n${oauthCallbackPanel}\n${oauthCallbackPage}`, new RegExp(text));
  }
});

test("Next 积分充值页读取账户并创建支付订单", () => {
  assert.match(billingPanel, /"use client"/);
  assert.match(billingPanel, /apiFetch\("\/api\/billing\/account"\)/);
  assert.match(billingPanel, /postJson<PaymentOrder>\("\/api\/billing\/payment-orders"/);
  assert.match(billingPanel, /apiFetch\("\/api\/billing\/subscriptions"\)/);
  assert.match(billingPanel, /postJson<SubscriptionPlan>\("\/api\/billing\/subscriptions"/);
  assert.match(billingPanel, /apiFetch\("\/api\/billing\/withdrawals"\)/);
  assert.match(billingPanel, /postJson<WithdrawalRequest>\("\/api\/billing\/withdrawals"/);
  assert.match(billingPanel, /postJson<WithdrawalRequest>\(`\/api\/admin\/billing\/withdrawals\/\$\{reviewWithdrawalId\}\/review`/);
  assert.match(billingPanel, /amount_cents: selectedOption\.amountCents/);
  assert.match(billingPanel, /latestOrder\.checkout_url/);
  assert.match(billingPanel, /href=\{latestOrder\.checkout_url\}/);
  assert.match(billingPanel, /target="_blank"/);
  assert.match(billingPanel, /postJson<CreditAccount>\("\/api\/admin\/billing\/credits"/);
  assert.match(billingPanel, /postJson<RevenueShare>\(`\/api\/admin\/billing\/works\/\$\{workId\}\/revenue`/);
  assert.match(billingPanel, /operator_id: operatorId/);
  assert.match(billingPanel, /target_user_id: targetUserId/);
  assert.match(billingPanel, /gross_credits: grossCredits/);
  assert.match(api, /export type RevenueShare/);
  assert.match(api, /export type SubscriptionPlan/);
  assert.match(api, /export type WithdrawalRequest/);
  for (const text of ["积分账户", "创建支付订单", "支付渠道", "支付订单已创建", "打开支付收银台", "会员订阅", "开通会员", "创作者提现", "提交提现申请", "审核提现", "暂无积分流水", "运营积分调账", "提交积分调账", "作品收益分账", "记录作品收益"]) {
    assert.match(`${billingPanel}\n${billingPage}`, new RegExp(text));
  }
});

test("Next 模板市场读取真实模板并支持复刻项目", () => {
  assert.match(templateMarketplace, /"use client"/);
  assert.match(templateMarketplace, /apiFetch\("\/api\/templates"\)/);
  assert.match(templateMarketplace, /postJson<Project>\("\/api\/projects"/);
  assert.match(templateMarketplace, /TemplateMarket/);
  assert.match(templateMarketplace, /fallbackTemplates/);
  assert.match(templateMarketplace, /href=\{`\/workspace\/\$\{createdProjectId\}`\}/);
  assert.match(templateMarketplace, /currentUserId/);
  assert.match(templateMarketplace, /owner_id: currentUserId\(\)/);
  assert.match(templateMarketplace, /template_id: template\.id/);
  assert.match(templateMarketplace, /project_type: "模板复刻"/);
  assert.match(templateMarketplace, /const \[projectTitle, setProjectTitle\]/);
  assert.match(templateMarketplace, /const \[aspectRatio, setAspectRatio\]/);
  assert.match(templateMarketplace, /const title = projectTitle\.trim\(\) \|\| `\$\{template\.name\} 复刻项目`/);
  assert.match(templateMarketplace, /aspect_ratio: aspectRatio/);
  assert.match(templates, /formatParams/);
  assert.match(templates, /item\.default_params/);
  assert.match(templates, /item\.example_inputs/);
  assert.match(templates, /item\.usage_count/);
  assert.match(templates, /item\.cover_url/);
  assert.match(templates, /item\.sample_video_url/);
  assert.match(api, /default_params\?: Record<string, unknown>/);
  assert.match(api, /example_inputs\?: Record<string, unknown>/);
  for (const text of ["复刻项目", "复刻项目标题", "目标画幅", "9:16 竖屏短视频", "16:9 横屏短片", "1:1 方形画布", "刷新模板", "模板复刻成功", "模板复刻失败，请稍后重试", "默认参数", "示例输入", "使用次数", "查看封面", "查看成片示例"]) {
    assert.match(`${templateMarketplace}\n${templates}\n${fallbackData}`, new RegExp(text));
  }
});

test("Next 创作工作台调用真实项目和生成接口", () => {
  assert.match(createWorkbench, /"use client"/);
  assert.match(createWorkbench, /currentUserId/);
  assert.match(createWorkbench, /apiFetch\("\/api\/templates"\)/);
  assert.match(createWorkbench, /fallbackTemplates/);
  assert.match(createWorkbench, /type Template/);
  assert.match(createWorkbench, /postJson<Project>\("\/api\/projects"/);
  assert.match(createWorkbench, /script\/analyze/);
  assert.match(createWorkbench, /type ProjectAnalysis/);
  assert.match(createWorkbench, /const \[aspectRatio, setAspectRatio\]/);
  assert.match(createWorkbench, /const \[selectedTemplateId, setSelectedTemplateId\]/);
  assert.match(createWorkbench, /aspect_ratio: aspectRatio/);
  assert.match(createWorkbench, /template_id: projectType === "模板复刻" \? selectedTemplateId : undefined/);
  assert.match(createWorkbench, /reference_image_url: projectType === "图片成片" \? referenceImageUrl : ""/);
  assert.match(createWorkbench, /projectType === "空白项目"/);
  assert.match(createWorkbench, /projectType === "模板复刻"/);
  assert.match(createWorkbench, /setProject\(\{ \.\.\.created, characters: analyzed\.characters, shots: analyzed\.shots/);
  assert.match(createWorkbench, /generate-image/);
  assert.match(createWorkbench, /batch-generate/);
  assert.match(createWorkbench, /timeline\/build/);
  assert.match(createWorkbench, /compose/);
  assert.match(createWorkbench, /href=\{`\/workspace\/\$\{project\.id\}`\}/);
  assert.match(createWorkbench, /window\.location\.href = `\/workspace\/\$\{created\.id\}`/);
  for (const text of ["创建项目并生成分镜草稿", "复刻模板并生成分镜草稿", "模板复刻项目已继承", "9:16 竖屏短视频", "16:9 横屏短片", "1:1 方形画布", "创建空白项目", "参考图 URL", "批量生成素材", "生成时间线", "合成成片", "任务队列", "积分余额不足", "进入项目工作台"]) {
    assert.match(createWorkbench, new RegExp(text));
  }
});

test("Next 独立项目工作台接入项目详情、素材、任务和导出接口", () => {
  assert.match(projectWorkspace, /"use client"/);
  assert.match(projectWorkspace, /apiFetch\(`\/api\/projects\/\$\{projectId\}\?user_id=/);
  assert.match(projectWorkspace, /apiFetch\(`\/api\/projects\/\$\{projectId\}\/tasks\?user_id=/);
  assert.match(projectWorkspace, /apiFetch\(`\/api\/projects\/\$\{projectId\}\/assets\?user_id=/);
  assert.match(projectWorkspace, /postJson<StoryboardShot>\(`\/api\/projects\/\$\{projectId\}\/shots`/);
  assert.match(projectWorkspace, /patchJson<Character>\(`\/api\/projects\/\$\{projectId\}\/characters\/\$\{character\.id\}`/);
  assert.match(projectWorkspace, /patchJson<StoryboardShot>\(`\/api\/projects\/\$\{projectId\}\/shots\/\$\{shot\.id\}`/);
  assert.match(projectWorkspace, /patchJson<SubtitleCue>\(`\/api\/projects\/\$\{projectId\}\/subtitles\/\$\{cue\.id\}`/);
  assert.match(projectWorkspace, /deleteJson<DeleteResult>\(`\/api\/projects\/\$\{projectId\}\/shots\/\$\{shotId\}`/);
  assert.match(projectWorkspace, /deleteJson<DeleteResult>\(`\/api\/projects\/\$\{projectId\}\/assets\/\$\{assetId\}`/);
  assert.match(projectWorkspace, /manualCharacters\.split/);
  assert.match(projectWorkspace, /generate-image/);
  assert.match(projectWorkspace, /generate-video/);
  assert.match(projectWorkspace, /generate-tts/);
  assert.match(projectWorkspace, /timeline\/build/);
  assert.match(projectWorkspace, /subtitles\/export/);
  assert.match(projectWorkspace, /compose/);
  assert.match(projectWorkspace, /postJson<Work>\(`\/api\/works\/\$\{projectId\}\/publish`/);
  assert.match(projectWorkspace, /publishTags\.split/);
  assert.match(projectWorkspace, /setLatestWork\(work\)/);
  assert.match(projectWorkspace, /updateCharacterDraft/);
  assert.match(projectWorkspace, /updateSubtitleDraft/);
  assert.match(projectWorkspace, /\/api\/comfy\/tasks\/\$\{taskId\}\/sync/);
  assert.match(projectWorkspace, /\/api\/tasks\/\$\{taskId\}\/\$\{action\}/);
  assert.match(templateMarketplace, /href=\{`\/workspace\/\$\{createdProjectId\}`\}/);
  for (const text of ["项目工作台", "项目结构", "角色设定", "保存角色设定", "参考图 URL", "统一风格提示词", "新增分镜", "新增手动分镜", "保存修订", "删除分镜", "分镜草稿", "时间线与字幕", "字幕文本", "字幕样式", "保存字幕修改", "项目任务队列", "项目素材库", "删除素材", "导出字幕", "合成成片", "发布审核", "提交发布审核", "作品已提交发布审核"]) {
    assert.match(projectWorkspace, new RegExp(text));
  }
});

test("Next 发布审核页接入真实审核、概览和巡检接口", () => {
  assert.match(adminReviewPanel, /"use client"/);
  assert.match(adminReviewPanel, /apiFetch\(`\/api\/works\?include_unpublished=true&user_id=/);
  assert.match(adminReviewPanel, /apiFetch\(`\/api\/admin\/billing\/withdrawals\?status=pending_review&operator_id=/);
  assert.match(adminReviewPanel, /apiFetch\(`\/api\/admin\/billing\/withdrawals\?status=approved&payout_status=failed&operator_id=/);
  assert.match(adminReviewPanel, /apiFetch\(`\/api\/admin\/billing\/withdrawals\?status=approved&payout_status=not_configured&operator_id=/);
  assert.match(adminReviewPanel, /apiFetch\(`\/api\/admin\/overview\?user_id=/);
  assert.match(adminReviewPanel, /apiFetch\(`\/api\/admin\/runtime-config\?user_id=/);
  assert.match(adminReviewPanel, /apiFetch\("\/api\/health"\)/);
  assert.match(adminReviewPanel, /postJson<ComfyUiPluginInstallReport>\("\/api\/admin\/comfyui\/plugin\/install"/);
  assert.match(adminReviewPanel, /postJson<Work>\(`\/api\/admin\/review\/\$\{workId\}`/);
  assert.match(adminReviewPanel, /postJson<WithdrawalRequest>\(`\/api\/admin\/billing\/withdrawals\/\$\{withdrawalId\}\/review`/);
  assert.match(adminReviewPanel, /postJson<WithdrawalRequest>\(`\/api\/admin\/billing\/withdrawals\/\$\{withdrawalId\}\/retry-payout`/);
  assert.match(adminReviewPanel, /postJson<StorageCleanupResult>\("\/api\/admin\/storage\/cleanup"/);
  assert.match(adminReviewPanel, /postJson<RunningTaskSyncResult>\("\/api\/admin\/tasks\/sync-running"/);
  assert.match(adminReviewPanel, /postJson<WorkflowRegistryProbeResult>\("\/api\/admin\/workflows\/probe"/);
  assert.match(adminReviewPanel, /action === "approve"/);
  assert.match(api, /export type AdminOverview/);
  assert.match(api, /export type AdminRuntimeConfig/);
  assert.match(api, /export type ComfyUiPluginInstallReport/);
  assert.match(api, /comfyui_plugin:/);
  assert.match(api, /workflow_registry:/);
  assert.match(api, /production_ready: boolean/);
  assert.match(api, /status: "pass" \| "warning" \| "blocker"/);
  assert.match(api, /export type WithdrawalRequest/);
  assert.match(api, /export type StorageCleanupResult/);
  assert.match(api, /export type StorageProbeResult/);
  assert.match(api, /export type PaymentWebhookProbeResult/);
  assert.match(api, /export type AlertProbeResult/);
  assert.match(api, /export type PayoutWebhookProbeResult/);
  assert.match(api, /export type WorkflowRegistryProbeResult/);
  assert.match(api, /export type RunningTaskSyncResult/);
  assert.match(adminReviewPanel, /api\/admin\/storage\/probe/);
  assert.match(adminReviewPanel, /api\/admin\/billing\/payment-webhook\/probe/);
  assert.match(adminReviewPanel, /api\/admin\/alerts\/probe/);
  assert.match(adminReviewPanel, /api\/admin\/billing\/payout-webhook\/probe/);
  assert.match(adminReviewPanel, /api\/admin\/workflows\/probe/);
  for (const text of ["审核队列", "提现审核", "通过提现", "驳回提现", "暂无待审核提现", "打款通知处理", "重试打款通知", "暂无待处理打款通知", "运营概览", "部署自检", "安装平台插件", "生产配置未就绪", "阻塞", "ComfyUI 插件", "工作流注册表", "访问令牌", "打款 Webhook", "巡检操作", "清理预检", "清理孤儿文件", "存储读写探针", "支付回调探针", "告警 Webhook 探针", "打款 Webhook 探针", "工作流注册表探针", "同步预检", "同步运行中任务", "暂无待审核作品"]) {
    assert.match(adminReviewPanel, new RegExp(text));
  }
});

test("Next 作品详情页接入真实作品接口和互动入口", () => {
  assert.match(workDetail, /"use client"/);
  assert.match(workDetail, /apiFetch\(`\/api\/works\/\$\{workId\}`\)/);
  assert.match(workDetail, /postJson<Work>\("\/api\/interactions"/);
  assert.match(workDetail, /interaction_type: interactionType/);
  assert.match(workDetail, /target_type: "work"/);
  assert.match(workDetail, /href=\{`\/users\/\$\{work\?\.author_id \|\| "system"\}`\}/);
  assert.match(gallery, /href=\{`\/works\/\$\{item\.id\}`\}/);
  for (const text of ["作品详情", "点赞", "收藏", "查看作者主页", "作品数据", "成片预览"]) {
    assert.match(workDetail, new RegExp(text));
  }
});

test("Next 作者主页读取真实作者聚合并支持关注", () => {
  assert.match(authorProfile, /"use client"/);
  assert.match(authorProfile, /apiFetch\(`\/api\/users\/\$\{userId\}`\)/);
  assert.match(authorProfile, /postJson<AuthorProfile>\("\/api\/interactions"/);
  assert.match(authorProfile, /target_type: "author"/);
  assert.match(authorProfile, /interaction_type: "follow"/);
  assert.match(authorProfile, /href=\{`\/works\/\$\{work\.id\}`\}/);
  assert.match(api, /export type AuthorProfile/);
  assert.match(api, /export function currentUserId/);
  assert.match(api, /export function saveCurrentUser/);
  for (const text of ["作者主页", "关注作者", "公开作品", "发布模板", "暂无公开作品"]) {
    assert.match(authorProfile, new RegExp(text));
  }
});

test("Next API client 统一透传平台令牌和用户会话", () => {
  assert.match(api, /export type Work/);
  assert.match(api, /export type Template/);
  assert.match(api, /export type Project/);
  assert.match(api, /export type GenerationTask/);
  assert.match(api, /export type CreditAccount/);
  assert.match(api, /export type PaymentOrder/);
  assert.match(api, /export type RevenueShare/);
  assert.match(api, /export type AuthResponse/);
  assert.match(api, /export type AuthorProfile/);
  assert.match(api, /export function savePlatformApiToken/);
  assert.match(api, /export function saveUserSessionToken/);
  assert.match(api, /export function saveCurrentUser/);
  assert.match(api, /export function currentUserId/);
  assert.match(api, /export async function apiFetch/);
  assert.match(api, /export async function postJson/);
  assert.match(api, /export async function patchJson/);
  assert.match(api, /export async function deleteJson/);
  assert.match(api, /export type DeleteResult/);
  assert.match(api, /window\.localStorage\.getItem\("platform_api_token"\)/);
  assert.match(api, /window\.localStorage\.getItem\("platform_user_session"\)/);
  assert.match(api, /window\.localStorage\.getItem\("platform_user_id"\)/);
  assert.match(api, /headers\.set\("Authorization", `Bearer \$\{token\}`\)/);
  assert.match(api, /headers\.set\("X-User-Session", sessionToken\)/);
});

test("Next Tailwind 配置使用克制的生产工具色板", () => {
  assert.match(tailwind, /content: \["\.\/app\/\*\*\/\*\.\{ts,tsx\}"/);
  assert.match(tailwind, /canvas: "#f6f7f9"/);
  assert.match(tailwind, /accent: "#1677ff"/);
  assert.match(tailwind, /borderRadius/);
});
