import { readFile } from "node:fs/promises";
import test from "node:test";
import assert from "node:assert/strict";

const html = await readFile(new URL("../frontend/index.html", import.meta.url), "utf8");
const js = await readFile(new URL("../frontend/app.js", import.meta.url), "utf8");
const css = await readFile(new URL("../frontend/styles.css", import.meta.url), "utf8");

test("前端首屏包含平台型核心工作流", () => {
  for (const text of ["作品广场", "创作工作台", "模板市场", "发布审核", "生成分镜草稿"]) {
    assert.match(html, new RegExp(text));
  }
});

test("前端绑定 ComfyUI 状态和工作流接口", () => {
  assert.match(js, /\/api\/comfy\/status/);
  assert.match(js, /\/api\/workflows/);
  assert.match(js, /ComfyUI 未连接/);
  assert.match(js, /item\.applicable_scenarios \|\| \[\]/);
});

test("前端请求统一透传平台访问令牌和用户会话", () => {
  assert.match(js, /function apiFetch/);
  assert.match(js, /window\.localStorage\.getItem\("platform_api_token"\)/);
  assert.match(js, /window\.localStorage\.getItem\("platform_user_session"\)/);
  assert.match(js, /headers\.set\("Authorization", `Bearer \$\{token\}`\)/);
  assert.match(js, /headers\.set\("X-User-Session", sessionToken\)/);
  assert.match(js, /return fetch\(url, \{ \.\.\.options, headers \}\)/);
});

test("前端提供账号注册登录并保存会话", () => {
  assert.match(html, /id="authForm"/);
  assert.match(html, /name="authUserId"/);
  assert.match(html, /name="authPassword"/);
  assert.match(html, /data-auth-action="login"/);
  assert.match(html, /data-auth-action="register"/);
  assert.match(js, /function submitAuth/);
  assert.match(js, /\/api\/auth\/register/);
  assert.match(js, /\/api\/auth\/login/);
  assert.match(js, /\/api\/auth\/session\/me/);
  assert.match(js, /setUserSessionToken\(data\.token\)/);
  assert.match(js, /loadCurrentSession\(\)/);
  assert.match(css, /\.account-form\s*\{/);
});

test("作品广场优先读取已发布作品接口", () => {
  assert.match(js, /function escapeHtml/);
  assert.match(js, /function escapeAttribute/);
  assert.match(js, /function safeUrl/);
  assert.match(js, /\.replaceAll\("&", "&amp;"\)/);
  assert.match(html, /data-category="AI 漫剧"/);
  for (const category of ["短片剧集", "动画短片", "概念设计", "经典衍生", "AI 漫剧", "广告短片", "精选画布"]) {
    assert.match(html, new RegExp(`data-category="${category}"`));
  }
  assert.match(js, /category: "经典衍生"/);
  assert.match(html, /id="sortSelect"/);
  assert.match(html, /id="workDetail"/);
  assert.match(js, /function buildWorksUrl/);
  assert.match(js, /params\.set\("category", activeCategory\)/);
  assert.match(js, /params\.set\("keyword", activeKeyword\)/);
  assert.match(js, /params\.set\("sort_by", activeSort\)/);
  assert.match(js, /apiFetch\(buildWorksUrl\(\)\)/);
  assert.match(js, /let currentWorks = fallbackWorks/);
  assert.match(js, /currentWorks = \(await response\.json\(\)\)\.map\(normalizeWork\)/);
  assert.match(js, /id: item\.id \|\| ""/);
  assert.match(js, /tags: item\.tags \|\| \[\]/);
  assert.match(js, /\(item\.tags \|\| \[\]\)\.join\(""\)/);
  assert.match(js, /暂无已发布作品/);
  assert.match(js, /escapeHtml\(item\.title\)/);
  assert.match(js, /escapeHtml\(item\.author\)/);
  assert.match(js, /view_count/);
  assert.match(js, /filterFallbackWorks/);
  assert.match(js, /activeCategory = button\.dataset\.category/);
  assert.match(js, /activeSort = event\.target\.value/);
  assert.match(css, /\.empty-state\s*\{/);
});

test("作品卡片支持点赞和收藏互动", () => {
  assert.match(js, /data-work-action="detail"/);
  assert.match(js, /apiFetch\(`\/api\/works\/\$\{workId\}`\)/);
  assert.match(js, /正在加载作品详情/);
  assert.match(js, /作品详情暂不可用/);
  assert.match(js, /renderWorkDetail\(await response\.json\(\)\)/);
  assert.match(js, /const videoUrl = safeUrl\(work\.video_url\)/);
  assert.match(js, /poster="\$\{coverUrl\}"/);
  assert.match(js, /模板来源/);
  assert.match(js, /escapeHtml\(work\.template_name \|\| "未使用模板"\)/);
  assert.match(js, /data-detail-interaction="like"/);
  assert.match(js, /data-detail-interaction="favorite"/);
  assert.match(js, /await loadWorks\(\)/);
  assert.match(js, /data-interaction-type="like"/);
  assert.match(js, /data-interaction-type="favorite"/);
  assert.match(js, /postJson\("\/api\/interactions"/);
  assert.match(js, /user_id: "demo_viewer"/);
  assert.match(js, /target_id: actions\.dataset\.workId/);
  assert.match(js, /interaction_type: button\.dataset\.interactionType/);
  assert.match(js, /interaction_type: interactionButton\.dataset\.detailInteraction/);
  assert.match(js, /await loadWorkDetail\(article\.dataset\.workId\)/);
  assert.match(js, /button\.textContent = "操作失败"/);
  assert.match(css, /\.work-actions\s*\{/);
  assert.match(css, /\.work-detail\s*\{/);
  assert.match(css, /\.work-player video,\s*\.work-player \.thumb\s*\{/);
});

test("作品详情可进入作者主页并关注作者", () => {
  assert.match(html, /id="authorProfile"/);
  assert.match(html, /id="authorCard"/);
  assert.match(html, /id="followAuthorButton"/);
  assert.match(html, /选择作品作者查看主页/);
  assert.match(js, /data-author-id="\$\{escapeAttribute\(work\.author_id \|\| "system"\)\}"/);
  assert.match(js, /function renderAuthorProfile/);
  assert.match(js, /apiFetch\(`\/api\/users\/\$\{authorId\}`\)/);
  assert.match(js, /正在加载作者主页/);
  assert.match(js, /作者主页暂不可用/);
  assert.match(js, /target_type: "author"/);
  assert.match(js, /interaction_type: "follow"/);
  assert.match(js, /button\.textContent = "已关注"/);
  assert.match(js, /button\.textContent = "关注失败"/);
  assert.match(css, /\.author-card article\s*\{/);
  assert.match(css, /\.author-avatar\s*\{/);
  assert.match(css, /\.author-works\s*\{/);
});

test("创作表单调用真实项目和脚本分析接口", () => {
  assert.match(html, /id="projectFormStatus"/);
  assert.match(html, /id="projectList"/);
  assert.match(html, /id="refreshProjects"/);
  assert.match(html, /id="characterList"/);
  assert.match(html, /id="refreshCharacters"/);
  assert.match(html, /id="composeButton"/);
  assert.match(html, /id="batchImageButton"/);
  assert.match(html, /id="batchTtsButton"/);
  assert.match(html, /id="buildTimelineButton"/);
  assert.match(html, /id="exportSubtitlesButton"/);
  assert.match(html, /id="publishButton"/);
  assert.match(html, /id="refreshExportButton"/);
  assert.match(html, /id="composeStatus"/);
  assert.match(html, /id="exportPanel"/);
  assert.match(html, /id="timelineList"/);
  assert.match(html, /id="refreshTimeline"/);
  assert.match(html, /name="referenceImageUrl"/);
  assert.match(html, /图片成片可填写首帧或角色参考图 URL/);
  assert.match(html, /id="newShotForm"/);
  assert.match(html, /id="newShotStatus"/);
  assert.match(html, /新增分镜/);
  assert.match(html, /id="shotList"/);
  assert.match(html, /id="assetList"/);
  assert.match(html, /id="refreshAssets"/);
  assert.match(html, /id="projectTaskList"/);
  assert.match(html, /id="refreshProjectTasks"/);
  assert.match(js, /postJson\("\/api\/projects"/);
  assert.match(js, /owner_id: "demo_creator"/);
  assert.match(js, /\/api\/projects\/\$\{project\.id\}\/script\/analyze/);
  assert.match(js, /script_analysis: "脚本分析"/);
  assert.match(js, /项目已创建，生成 \$\{analysis\.shots\.length\} 个分镜草稿/);
  assert.match(js, /renderShots\(analysis\.shots, project\.id\)/);
  assert.match(js, /renderCharacters\(analysis\.characters, project\.id\)/);
  assert.match(js, /await loadProjectTasks\(project\.id\)/);
  assert.match(js, /await loadProjectAssets\(project\.id\)/);
  assert.match(js, /currentProjectId = project\.id/);
  assert.match(js, /projectType !== "空白项目" && !script/);
  assert.match(js, /画面描述不能为空。/);
  assert.match(js, /reference_image_url: referenceImageUrl/);
  assert.match(js, /空白项目已创建：\$\{project\.title\}/);
  assert.match(js, /请补充分镜后继续生成/);
  assert.match(js, /图片成片项目已创建，生成 1 个镜头草稿/);
  assert.match(js, /function createManualShot/);
  assert.match(js, /\/api\/projects\/\$\{currentProjectId\}\/shots/);
  assert.match(js, /name="newShotNarration"|newShotNarration/);
  assert.match(js, /newShotVisual/);
  assert.match(js, /已添加分镜 #\$\{shot\.index\}/);
  assert.match(js, /分镜添加失败，请稍后重试/);
  assert.match(js, /document\.querySelector\("#newShotForm"\)\.addEventListener/);
  assert.match(js, /暂无分镜草稿/);
  assert.match(js, /name="shotNarration"/);
  assert.match(js, /name="shotVisualDescription"/);
  assert.match(js, /name="shotPrompt"/);
  assert.match(js, /data-shot-action="save-shot"/);
  assert.match(js, /data-shot-action="delete-shot"/);
  assert.match(js, /\/api\/projects\/\$\{item\.dataset\.projectId\}\/shots\/\$\{item\.dataset\.shotId\}/);
  assert.match(js, /method: "PATCH"/);
  assert.match(js, /method: "DELETE"/);
  assert.match(js, /分镜已保存，时间线需重新生成/);
  assert.match(js, /分镜已更新，请重新生成时间线/);
  assert.match(js, /分镜保存失败，请稍后重试/);
  assert.match(js, /分镜已删除，请重新生成时间线/);
  assert.match(js, /分镜删除失败，请稍后重试/);
  assert.match(js, /data-shot-action="generate-image"/);
  assert.match(js, /data-shot-action="generate-video"/);
  assert.match(js, /data-shot-action="generate-tts"/);
  assert.match(js, /task-event-log/);
  assert.match(js, /name="firstFrameUrl"/);
  assert.match(js, /\/api\/projects\/\$\{item\.dataset\.projectId\}\/shots\/\$\{item\.dataset\.shotId\}\/generate-image/);
  assert.match(js, /\/api\/projects\/\$\{item\.dataset\.projectId\}\/shots\/\$\{item\.dataset\.shotId\}\/generate-video/);
  assert.match(js, /\/api\/projects\/\$\{item\.dataset\.projectId\}\/shots\/\$\{item\.dataset\.shotId\}\/generate-tts/);
  assert.match(js, /voice: "zh-CN-XiaoxiaoNeural"/);
  assert.match(js, /first_frame_url: firstFrameUrl/);
  assert.match(js, /首帧图片 URL 不能为空/);
  assert.match(js, /function submitGeneratedTask/);
  assert.match(js, /\/api\/tasks\/\$\{task\.id\}\/submit/);
  assert.match(js, /user_id: "demo_creator"/);
  assert.doesNotMatch(js, /workflow_payload:\s*\{/);
  assert.doesNotMatch(js, /"1":\s*\{\s*inputs/);
  assert.match(js, /分镜图任务已提交：\$\{submitted\.id\}/);
  assert.match(js, /镜头视频任务已提交：\$\{submitted\.id\}/);
  assert.match(js, /旁白配音任务已提交：\$\{submitted\.id\}/);
  assert.match(js, /data-shot-action='sync-image'/);
  assert.match(js, /data-shot-action = "sync-video"|data-shot-action="sync-video"|button\.dataset\.shotAction = "sync-video"/);
  assert.match(js, /button\.dataset\.shotAction = "sync-tts"/);
  assert.match(js, /\/api\/comfy\/tasks\/\$\{item\.dataset\.imageTaskId\}\/sync/);
  assert.match(js, /\/api\/comfy\/tasks\/\$\{item\.dataset\.videoTaskId\}\/sync/);
  assert.match(js, /\/api\/comfy\/tasks\/\$\{item\.dataset\.ttsTaskId\}\/sync/);
  assert.match(js, /\/api\/tasks\/\$\{taskId\}\?user_id=demo_creator/);
  assert.match(js, /任务状态：\$\{task\.status\} · \$\{task\.progress\}%/);
  assert.match(js, /function renderTaskEvents/);
  assert.match(js, /task\.events \|\| \[\]/);
  assert.match(js, /暂无任务日志/);
  assert.match(js, /escapeHtml\(event\.message\)/);
  assert.match(js, /button\.textContent = "同步失败"/);
  assert.match(js, /button\.textContent = "生成失败"/);
  assert.match(js, /请先生成分镜草稿/);
  assert.match(js, /function batchGenerateProject/);
  assert.match(js, /await loadProjectTasks\(\)/);
  assert.match(js, /\/api\/projects\/\$\{currentProjectId\}\/batch-generate/);
  assert.match(js, /task_types: taskTypes/);
  assert.match(js, /submit: true/);
  assert.match(js, /批量任务已提交：\$\{result\.task_count\} 个任务/);
  assert.match(js, /正在批量创建分镜图任务/);
  assert.match(js, /正在批量创建旁白配音任务/);
  assert.match(js, /批量生成失败，请稍后重试/);
  assert.match(js, /setTaskState\(1, "批量生成中"\)/);
  assert.match(js, /setTaskState\(3, "批量生成中"\)/);
  assert.match(js, /function buildProjectTimeline/);
  assert.match(js, /\/api\/projects\/\$\{currentProjectId\}\/timeline\/build/);
  assert.match(js, /正在生成时间线与字幕/);
  assert.match(js, /时间线已生成：\$\{result\.timeline\.length\} 个镜头 · \$\{result\.duration_seconds\}s/);
  assert.match(js, /时间线生成失败，请稍后重试/);
  assert.match(js, /duration_per_shot: 4/);
  assert.match(js, /\/api\/projects\/\$\{currentProjectId\}\/compose/);
  assert.match(js, /正在创建合成任务/);
  assert.match(js, /合成任务已提交：\$\{submitted\.id\}，完成后可在任务队列同步归档/);
  assert.match(js, /await loadProjectTimeline\(\)/);
  assert.match(js, /function renderExportPanel/);
  assert.match(js, /function loadProjectExport/);
  assert.match(js, /apiFetch\(`\/api\/projects\/\$\{projectId\}\?user_id=demo_creator`\)/);
  assert.match(js, /预览成片/);
  assert.match(js, /查看封面/);
  assert.match(js, /成片已导出，可预览/);
  assert.match(js, /导出状态暂不可用/);
  assert.match(js, /document\.querySelector\("#refreshExportButton"\)\.addEventListener/);
  assert.match(html, /name="publishTitle"/);
  assert.match(html, /name="publishCategory"/);
  assert.match(html, /name="publishTags"/);
  assert.match(html, /name="publishCoverUrl"/);
  assert.match(html, /name="publishDescription"/);
  assert.match(js, /\/api\/works\/\$\{currentProjectId\}\/publish/);
  assert.match(js, /正在检查成片导出/);
  assert.match(js, /请先完成成片导出/);
  assert.match(js, /if \(!project \|\| !project\.final_video_url\)/);
  assert.match(js, /正在提交审核/);
  assert.match(js, /category: document\.querySelector\("\[name='publishCategory'\]"\)\.value/);
  assert.match(js, /tags: document\.querySelector\("\[name='publishTags'\]"\)\.value\.trim\(\)/);
  assert.match(js, /cover_url: document\.querySelector\("\[name='publishCoverUrl'\]"\)\.value\.trim\(\)/);
  assert.match(js, /已提交审核：\$\{work\.title\}/);
  assert.match(js, /提交审核失败，请稍后重试/);
  assert.match(js, /await loadReviewQueue\(\)/);
  assert.match(js, /项目标题不能为空。/);
  assert.match(js, /脚本文本不能为空。/);
});

test("工作台可查看并恢复项目草稿", () => {
  assert.match(html, /项目草稿/);
  assert.match(html, /暂无项目草稿/);
  assert.match(html, /刷新项目/);
  assert.match(js, /function renderProjects/);
  assert.match(js, /function loadProjects/);
  assert.match(js, /function loadProjectWorkspace/);
  assert.match(js, /function projectStepLabel/);
  assert.match(js, /function projectStatusLabel/);
  assert.match(js, /apiFetch\("\/api\/projects\?owner_id=demo_creator"\)/);
  assert.match(js, /apiFetch\(`\/api\/projects\/\$\{projectId\}\?user_id=demo_creator`\)/);
  assert.match(js, /data-project-action="open"/);
  assert.match(js, /currentProjectId = project\.id/);
  assert.match(js, /renderCharacters\(project\.characters \|\| \[\], project\.id\)/);
  assert.match(js, /renderShots\(project\.shots \|\| \[\], project\.id\)/);
  assert.match(js, /escapeAttribute\(projectId\)/);
  assert.match(js, /escapeHtml\(shot\.narration\)/);
  assert.match(js, /escapeHtml\(shot\.prompt\)/);
  assert.match(js, /renderTimeline\(project\.timeline \|\| \[\], project\.subtitles \|\| \[\]\)/);
  assert.match(js, /renderExportPanel\(project\)/);
  assert.match(js, /await loadProjectTasks\(project\.id\)/);
  assert.match(js, /await loadProjectAssets\(project\.id\)/);
  assert.match(js, /已加载项目：\$\{project\.title\}/);
  assert.match(js, /项目列表暂不可用/);
  assert.match(js, /项目加载失败，请稍后重试/);
  assert.match(js, /document\.querySelector\("#refreshProjects"\)\.addEventListener/);
  assert.match(js, /document\.querySelector\("#projectList"\)\.addEventListener/);
  assert.match(js, /await loadProjects\(\)/);
  assert.match(css, /\.project-list-panel\s*\{/);
  assert.match(css, /\.project-list\s*\{/);
  assert.match(css, /\.project-list-item\s*\{/);
});

test("工作台可编辑角色设定", () => {
  assert.match(html, /角色设定/);
  assert.match(html, /暂无角色设定/);
  assert.match(html, /刷新角色/);
  assert.match(js, /function renderCharacters/);
  assert.match(js, /name="characterName"/);
  assert.match(js, /name="characterDescription"/);
  assert.match(js, /name="characterStylePrompt"/);
  assert.match(js, /data-character-action="save"/);
  assert.match(js, /patchJson\(`\/api\/projects\/\$\{item\.dataset\.projectId\}\/characters\/\$\{item\.dataset\.characterId\}`/);
  assert.match(js, /角色设定已保存/);
  assert.match(js, /角色保存失败，请稍后重试/);
  assert.match(js, /document\.querySelector\("#refreshCharacters"\)\.addEventListener/);
  assert.match(js, /document\.querySelector\("#characterList"\)\.addEventListener/);
  assert.match(css, /\.character-panel\s*\{/);
  assert.match(css, /\.character-list\s*\{/);
  assert.match(css, /\.character-item\s*\{/);
});

test("工作台展示时间线与字幕并可生成", () => {
  assert.match(html, /时间线与字幕/);
  assert.match(html, /暂无时间线草稿/);
  assert.match(html, /导出字幕/);
  assert.match(html, /刷新时间线/);
  assert.match(js, /function renderTimeline/);
  assert.match(js, /function loadProjectTimeline/);
  assert.match(js, /function exportProjectSubtitles/);
  assert.match(js, /function transitionLabel/);
  assert.match(js, /function formatSeconds/);
  assert.match(js, /apiFetch\(`\/api\/projects\/\$\{projectId\}\?user_id=demo_creator`\)/);
  assert.match(js, /renderTimeline\(project\.timeline \|\| \[\], project\.subtitles \|\| \[\]\)/);
  assert.match(js, /时间线暂不可用/);
  assert.match(js, /name="subtitleText"/);
  assert.match(js, /data-subtitle-action="save"/);
  assert.match(js, /patchJson\(`\/api\/projects\/\$\{currentProjectId\}\/subtitles\/\$\{item\.dataset\.subtitleId\}`/);
  assert.match(js, /字幕已保存/);
  assert.match(js, /字幕保存失败，请稍后重试/);
  assert.match(js, /\/api\/projects\/\$\{currentProjectId\}\/subtitles\/export/);
  assert.match(js, /正在导出字幕文件/);
  assert.match(js, /字幕已导出：\$\{asset\.url\}/);
  assert.match(js, /字幕导出失败，请稍后重试/);
  assert.match(js, /await loadProjectAssets\(\)/);
  assert.match(js, /document\.querySelector\("#buildTimelineButton"\)\.addEventListener/);
  assert.match(js, /document\.querySelector\("#exportSubtitlesButton"\)\.addEventListener/);
  assert.match(js, /document\.querySelector\("#timelineList"\)\.addEventListener/);
  assert.match(js, /document\.querySelector\("#refreshTimeline"\)\.addEventListener/);
  assert.match(js, /renderTimeline\(\[\]\)/);
  assert.match(css, /\.timeline-panel\s*\{/);
  assert.match(css, /\.timeline-list\s*\{/);
  assert.match(css, /\.timeline-item\s*\{/);
  assert.match(css, /\.timeline-actions\s*\{/);
});

test("工作台展示项目素材库并可刷新", () => {
  assert.match(html, /项目素材库/);
  assert.match(html, /刷新素材/);
  assert.match(html, /暂无归档素材/);
  assert.match(js, /function renderProjectAssets/);
  assert.match(js, /function assetTypeLabel/);
  assert.match(js, /function formatAssetMeta/);
  assert.match(js, /function deleteJson/);
  assert.match(js, /audio: "配音音频"/);
  assert.match(js, /asset-meta/);
  assert.match(js, /item\.width && item\.height/);
  assert.match(js, /item\.duration_seconds/);
  assert.match(js, /item\.mime_type/);
  assert.match(js, /item\.content_hash/);
  assert.match(js, /暂无素材元数据/);
  assert.match(js, /data-asset-action="delete"/);
  assert.match(js, /apiFetch\(`\/api\/projects\/\$\{projectId\}\/assets\?user_id=demo_creator`\)/);
  assert.match(js, /renderProjectAssets\(await response\.json\(\)\)/);
  assert.match(js, /method: "DELETE"/);
  assert.match(js, /\/api\/projects\/\$\{currentProjectId\}\/assets\/\$\{item\.dataset\.assetId\}/);
  assert.match(js, /素材已删除/);
  assert.match(js, /素材删除失败，请稍后重试/);
  assert.match(js, /await loadProjectExport\(\)/);
  assert.match(js, /素材库暂不可用/);
  assert.match(js, /if \(task\.status === "completed"\) await loadProjectAssets\(item\.dataset\.projectId\)/);
  assert.match(js, /document\.querySelector\("#refreshAssets"\)\.addEventListener/);
  assert.match(js, /document\.querySelector\("#assetList"\)\.addEventListener/);
  assert.match(js, /renderProjectAssets\(\[\]\)/);
  assert.match(css, /\.asset-library\s*\{/);
  assert.match(css, /\.asset-list\s*\{/);
  assert.match(css, /\.asset-item\s*\{/);
  assert.match(css, /\.asset-meta\s*\{/);
  assert.match(css, /\.asset-actions\s*\{/);
});

test("工作台展示项目任务队列并可刷新", () => {
  assert.match(html, /项目任务队列/);
  assert.match(html, /暂无项目任务/);
  assert.match(html, /刷新任务/);
  assert.match(html, /id="projectTaskStatusFilter"/);
  assert.match(html, /任务状态筛选/);
  assert.match(js, /function renderProjectTasks/);
  assert.match(js, /function taskTypeLabel/);
  assert.match(js, /function taskActionButtons/);
  assert.match(js, /function controlProjectTask/);
  assert.match(js, /new URLSearchParams\(\{ user_id: "demo_creator" \}\)/);
  assert.match(js, /params\.set\("status", statusFilter\)/);
  assert.match(js, /apiFetch\(`\/api\/projects\/\$\{projectId\}\/tasks\?\$\{params\.toString\(\)\}`\)/);
  assert.match(js, /renderProjectTasks\(await response\.json\(\)\)/);
  assert.match(js, /data-task-action="cancel"/);
  assert.match(js, /data-task-action="retry"/);
  assert.match(js, /data-task-action="sync"/);
  assert.match(js, /\/api\/tasks\/\$\{taskId\}\/cancel/);
  assert.match(js, /\/api\/tasks\/\$\{taskId\}\/retry/);
  assert.match(js, /\/api\/comfy\/tasks\/\$\{taskId\}\/sync/);
  assert.match(js, /user_id: "demo_creator", reason: "用户在工作台取消任务。"/);
  assert.match(js, /用户在工作台取消任务。/);
  assert.match(js, /任务已取消，可在队列中重试/);
  assert.match(js, /任务已重置为可重试状态/);
  assert.match(js, /任务已同步：\$\{task\.status\} · \$\{task\.progress\}%/);
  assert.match(js, /任务操作失败，请稍后重试/);
  assert.match(js, /document\.querySelector\("#projectTaskList"\)\.addEventListener/);
  assert.match(js, /document\.querySelector\("#projectTaskStatusFilter"\)\.addEventListener\("change"/);
  assert.match(js, /任务队列暂不可用/);
  assert.match(js, /document\.querySelector\("#refreshProjectTasks"\)\.addEventListener/);
  assert.match(js, /renderProjectTasks\(\[\]\)/);
  assert.match(css, /\.project-task-panel\s*\{/);
  assert.match(css, /\.project-task-item\s*\{/);
  assert.match(css, /\.project-task-actions\s*\{/);
});

test("模板市场读取真实模板并支持复刻项目", () => {
  assert.match(html, /id="templateList"/);
  assert.match(html, /id="refreshTemplates"/);
  assert.match(js, /apiFetch\("\/api\/templates"\)/);
  assert.match(js, /renderTemplates\(await response\.json\(\)\)/);
  assert.match(js, /class="workflow-item template-card"/);
  assert.match(js, /class="template-cover"/);
  assert.match(js, /class="template-tags"/);
  assert.match(js, /示例输入：\$\{formatTemplateExample\(item\.example_inputs \|\| \{\}\)\}/);
  assert.match(js, /默认参数：\$\{formatTemplateExample\(item\.default_params \|\| \{\}\)\}/);
  assert.match(js, /成片示例/);
  assert.match(js, /function formatTemplateExample/);
  assert.match(js, /data-template-action="use"/);
  assert.match(js, /template_id: item\.dataset\.templateId/);
  assert.match(js, /owner_id: "demo_creator"/);
  assert.match(js, /project_type: "模板复刻"/);
  assert.match(js, /正在从模板创建项目/);
  assert.match(js, /已从模板创建项目：\$\{project\.title\}/);
  assert.match(js, /暂无可用模板/);
  assert.match(css, /\.template-card\s*\{/);
  assert.match(css, /\.template-cover\s*\{/);
  assert.match(css, /\.template-tags span\s*\{/);
});

test("发布审核队列调用真实审核接口", () => {
  assert.match(html, /id="platformHealth"/);
  assert.match(html, /id="adminOverview"/);
  assert.match(html, /id="refreshAdminOverview"/);
  assert.match(html, /平台健康检查中/);
  assert.match(html, /运营概览加载中/);
  assert.match(html, /刷新运营状态/);
  assert.match(js, /function renderPlatformHealth/);
  assert.match(js, /function loadPlatformHealth/);
  assert.match(js, /function refreshOperationsStatus/);
  assert.match(js, /function renderAdminOverview/);
  assert.match(js, /function loadAdminOverview/);
  assert.match(js, /function formatCounts/);
  assert.match(js, /function formatBytes/);
  assert.match(js, /apiFetch\("\/api\/health"\)/);
  assert.match(js, /renderPlatformHealth\(await response\.json\(\)\)/);
  assert.match(js, /平台健康暂不可用/);
  assert.match(js, /平台健康：/);
  assert.match(js, /暂无告警/);
  assert.match(js, /ComfyUI：/);
  assert.match(js, /apiFetch\("\/api\/admin\/overview\?user_id=system_admin"\)/);
  assert.match(js, /renderAdminOverview\(await response\.json\(\)\)/);
  assert.match(js, /运营概览暂不可用/);
  assert.match(js, /storage_total_bytes/);
  assert.match(js, /missing_asset_reference_count/);
  assert.match(js, /失效引用/);
  assert.match(js, /id="cleanupStorageButton"/);
  assert.match(js, /function cleanupStorage/);
  assert.match(js, /\/api\/admin\/storage\/cleanup/);
  assert.match(js, /清理孤儿素材文件/);
  assert.match(js, /已清理 \$\{result\.deleted_file_count \|\| 0\} 个孤儿文件/);
  assert.match(js, /latest_failed_tasks/);
  assert.match(js, /await refreshOperationsStatus\(\)/);
  assert.match(js, /document\.querySelector\("#refreshAdminOverview"\)\.addEventListener/);
  assert.match(js, /document\.querySelector\("#adminOverview"\)\.addEventListener/);
  assert.match(html, /id="reviewList"/);
  assert.match(js, /\/api\/works\?include_unpublished=true&user_id=system_admin/);
  assert.match(js, /review_status === "pending_review"/);
  assert.match(js, /review_status === "published"/);
  assert.match(js, /function reviewStatusLabel/);
  assert.match(js, /data-review-action="approve"/);
  assert.match(js, /data-review-action="reject"/);
  assert.match(js, /data-review-action="offline"/);
  assert.match(js, /\/api\/admin\/review\/\$\{item\.dataset\.workId\}/);
  assert.match(js, /user_id: "system_admin"/);
  assert.match(js, /审核队列暂不可用/);
  assert.match(js, /暂无待审核作品/);
  assert.match(css, /\.platform-health\s*\{/);
  assert.match(css, /\.health-status\s*\{/);
  assert.match(css, /\.health-alert\s*\{/);
  assert.match(css, /\.admin-overview\s*\{/);
  assert.match(css, /\.overview-grid\s*\{/);
  assert.match(css, /\.overview-detail\s*\{/);
});

test("界面样式保持生产工具布局", () => {
  assert.match(css, /\.app-shell\s*\{/);
  assert.match(css, /grid-template-columns: 240px minmax\(0, 1fr\)/);
  assert.match(css, /\.workspace-grid\s*\{/);
  assert.match(css, /\.form-status\.failed\s*\{/);
  assert.match(css, /\.compose-bar\s*\{/);
  assert.match(css, /\.compose-status\s*\{/);
  assert.match(css, /\.shot-create-panel\s*\{/);
  assert.match(css, /\.shot-create-form\s*\{/);
  assert.match(css, /\.export-panel\s*\{/);
  assert.match(css, /\.export-result\s*\{/);
  assert.match(css, /\.ghost-button\.full\s*\{/);
  assert.match(css, /\.empty-state\.compact\s*\{/);
  assert.match(css, /\.shot-item\s*\{/);
  assert.match(css, /\.shot-frame-input\s*\{/);
  assert.match(css, /\.shot-actions\s*\{/);
  assert.match(css, /\.shot-task-status\s*\{/);
  assert.match(css, /\.task-event-log\s*\{/);
  assert.match(css, /\.project-task-list\s*\{/);
  assert.match(css, /\.author-card dl\s*\{/);
  assert.doesNotMatch(css, /border-radius:\s*(2[0-9]|[3-9][0-9])px/);
});
