import type { Template, Work } from "./api";

export const categories = ["全部", "创作者挑战赛", "Seedance 2.0", "TV Show", "精选画布", "短片剧集", "AI 漫剧", "动画短片", "概念设计", "经典衍生", "广告短片"];

export const fallbackWorks: Work[] = [
  { id: "demo_1", title: "雨夜车站", category: "AI 漫剧", author_id: "青禾工作室", cover_url: "/storage/covers/rain-station.jpg", video_url: "/storage/final/rain-station.mp4", template_name: "Flux 分镜图生成", tags: ["悬疑", "雨夜", "漫剧"], view_count: 28000, like_count: 310, favorite_count: 88 },
  { id: "demo_challenge", title: "十五秒反转挑战", category: "创作者挑战赛", author_id: "挑战赛精选", cover_url: "/storage/covers/challenge-reversal.jpg", video_url: "/storage/final/challenge-reversal.mp4", template_name: "创作者挑战赛参赛片", tags: ["挑战赛", "反转", "短片"], view_count: 33000, like_count: 428, favorite_count: 126 },
  { id: "demo_seedance", title: "Seedance 雨夜回眸", category: "Seedance 2.0", author_id: "Seedance 体验官", cover_url: "/storage/covers/seedance-rain.jpg", video_url: "/storage/final/seedance-rain.mp4", template_name: "Seedance 2.0 快速体验", tags: ["Seedance", "图生视频", "运镜"], view_count: 36000, like_count: 512, favorite_count: 144 },
  { id: "demo_tv_show", title: "未来新闻冷开场", category: "TV Show", author_id: "TV Show 实验室", cover_url: "/storage/covers/tv-show-open.jpg", video_url: "/storage/final/tv-show-open.mp4", template_name: "TV Show 剧集开场", tags: ["TV Show", "主持人", "剧集"], view_count: 29500, like_count: 356, favorite_count: 102 },
  { id: "demo_2", title: "赛博巷口", category: "概念设计", author_id: "镜头实验室", cover_url: "/storage/covers/cyber-alley.jpg", video_url: "/storage/final/cyber-alley.mp4", template_name: "Wan2.1 镜头视频生成", tags: ["赛博", "霓虹", "短片"], view_count: 14000, like_count: 176, favorite_count: 52 },
  { id: "demo_3", title: "山海旧梦", category: "经典衍生", author_id: "神话改编组", cover_url: "/storage/covers/shanhai-dream.jpg", template_name: "中文旁白配音", tags: ["神话", "国风", "旁白"], view_count: 19000, like_count: 238, favorite_count: 76 }
];

export const fallbackTemplates: Template[] = [
  { id: "selfhost/image_flux", name: "Flux 分镜图生成", category: "AI 漫剧", workflow_key: "selfhost/image_flux", description: "根据分镜画面描述生成竖屏首帧。", cover_url: "/storage/templates/flux-storyboard-cover.jpg", sample_video_url: "/storage/templates/flux-storyboard-sample.mp4", default_params: { width: 768, height: 1344, seed: -1 }, example_inputs: { prompt: "雨夜车站，女主回头看见旧护身符" }, applicable_scenarios: ["分镜首帧", "角色海报"], usage_count: 12 },
  { id: "quick/creator_challenge_entry", name: "创作者挑战赛参赛片", category: "创作者挑战赛", workflow_key: "creator_challenge_entry", description: "围绕挑战赛 brief 自动铺设海报首帧、短片镜头、宣发口播和成片提交链路。", cover_url: "/storage/templates/creator-challenge-cover.jpg", sample_video_url: "/storage/templates/creator-challenge-sample.mp4", default_params: { duration: 5, fps: 24, transition: "fade" }, example_inputs: { script: "15 秒讲清一个反转瞬间，主角在霓虹雨夜打开信封。" }, applicable_scenarios: ["创作者挑战赛", "短片挑战", "反转短剧"], usage_count: 21 },
  { id: "quick/seedance2_image_video", name: "Seedance 2.0 快速体验", category: "Seedance 2.0", workflow_key: "seedance2_image_video", description: "参考图和动作提示词接入图生视频，再进入成片合成。", cover_url: "/storage/templates/seedance2-cover.jpg", sample_video_url: "/storage/templates/seedance2-sample.mp4", default_params: { duration: 5, fps: 24, camera_motion: "缓慢推进" }, example_inputs: { prompt: "电影感雨夜车站，主角回头，镜头缓慢推进", first_frame_url: "/storage/reference/hero.png" }, applicable_scenarios: ["Seedance", "图生视频", "快速体验"], usage_count: 18 },
  { id: "quick/tv_show_storyboard", name: "TV Show 剧集开场", category: "TV Show", workflow_key: "tv_show_storyboard", description: "剧集脚本拆成分镜图、镜头视频、角色旁白和合成链路。", cover_url: "/storage/templates/tv-show-cover.jpg", sample_video_url: "/storage/templates/tv-show-sample.mp4", default_params: { duration: 6, transition: "fade", voice: "zh-CN-XiaoxiaoNeural" }, example_inputs: { script: "女主持走入未来新闻演播厅，屏幕出现本集主题。" }, applicable_scenarios: ["TV Show", "剧集开场", "主持人口播"], usage_count: 14 },
  { id: "selfhost/video_wan2.1_fusionx", name: "Wan2.1 镜头视频生成", category: "短片剧集", workflow_key: "selfhost/video_wan2.1_fusionx", description: "基于首帧和动作描述生成镜头视频。", cover_url: "/storage/templates/wan-motion-cover.jpg", sample_video_url: "/storage/templates/wan-motion-sample.mp4", default_params: { duration: 4, fps: 16 }, example_inputs: { prompt: "主角穿过霓虹雨巷", first_frame_url: "/storage/examples/rain-alley-first-frame.png" }, applicable_scenarios: ["镜头视频", "动画短片"], usage_count: 8 },
  { id: "selfhost/tts_edge", name: "中文旁白配音", category: "旁白配音", workflow_key: "selfhost/tts_edge", description: "为分镜旁白生成中文音频。", cover_url: "/storage/templates/tts-narration-cover.jpg", sample_video_url: "/storage/templates/tts-narration-sample.mp4", default_params: { voice: "zh-CN-XiaoxiaoNeural", rate: 1 }, example_inputs: { text: "她终于在雨声里听见了那句迟来的告别。" }, applicable_scenarios: ["旁白配音", "字幕口播"], usage_count: 6 }
];
